//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PowerAutomate.Desktop.Modules.Identity.Actions.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PowerAutomate.Desktop.Modules.Identity.Actions.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indicates that there was a problem when executing the operation..
        /// </summary>
        public static string Error_UnknownError_Description {
            get {
                return ResourceManager.GetString("Error_UnknownError_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation failed.
        /// </summary>
        public static string Error_UnknownError_FriendlyName {
            get {
                return ResourceManager.GetString("Error_UnknownError_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The authority..
        /// </summary>
        public static string GetAccessToken_Authority_Description {
            get {
                return ResourceManager.GetString("GetAccessToken_Authority_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authority.
        /// </summary>
        public static string GetAccessToken_Authority_FriendlyName {
            get {
                return ResourceManager.GetString("GetAccessToken_Authority_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The client identifier..
        /// </summary>
        public static string GetAccessToken_ClientId_Description {
            get {
                return ResourceManager.GetString("GetAccessToken_ClientId_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client ID.
        /// </summary>
        public static string GetAccessToken_ClientId_FriendlyName {
            get {
                return ResourceManager.GetString("GetAccessToken_ClientId_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The client secret..
        /// </summary>
        public static string GetAccessToken_ClientSecret_Description {
            get {
                return ResourceManager.GetString("GetAccessToken_ClientSecret_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client Secret.
        /// </summary>
        public static string GetAccessToken_ClientSecret_FriendlyName {
            get {
                return ResourceManager.GetString("GetAccessToken_ClientSecret_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gets the access token..
        /// </summary>
        public static string GetAccessToken_Description {
            get {
                return ResourceManager.GetString("GetAccessToken_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get access token.
        /// </summary>
        public static string GetAccessToken_FriendlyName {
            get {
                return ResourceManager.GetString("GetAccessToken_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The scopes..
        /// </summary>
        public static string GetAccessToken_Scopes_Description {
            get {
                return ResourceManager.GetString("GetAccessToken_Scopes_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scopes.
        /// </summary>
        public static string GetAccessToken_Scopes_FriendlyName {
            get {
                return ResourceManager.GetString("GetAccessToken_Scopes_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get an access token..
        /// </summary>
        public static string GetAccessToken_Summary {
            get {
                return ResourceManager.GetString("GetAccessToken_Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The token..
        /// </summary>
        public static string GetAccessToken_Token_Description {
            get {
                return ResourceManager.GetString("GetAccessToken_Token_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Token.
        /// </summary>
        public static string GetAccessToken_Token_FriendlyName {
            get {
                return ResourceManager.GetString("GetAccessToken_Token_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Perform operations related to Microsoft Authentication..
        /// </summary>
        public static string Identity_Description {
            get {
                return ResourceManager.GetString("Identity_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microsoft Authentication.
        /// </summary>
        public static string Identity_FriendlyName {
            get {
                return ResourceManager.GetString("Identity_FriendlyName", resourceCulture);
            }
        }
    }
}
