//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PowerAutomate.Desktop.Modules.AzureKeyVault.Actions.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PowerAutomate.Desktop.Modules.AzureKeyVault.Actions.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Perform operations related to Azure Key Vault..
        /// </summary>
        public static string AzureKeyVault_Description {
            get {
                return ResourceManager.GetString("AzureKeyVault_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Azure Key Vault.
        /// </summary>
        public static string AzureKeyVault_FriendlyName {
            get {
                return ResourceManager.GetString("AzureKeyVault_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indicates that there was a problem when executing the operation..
        /// </summary>
        public static string Error_UnknownError_Description {
            get {
                return ResourceManager.GetString("Error_UnknownError_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation failed.
        /// </summary>
        public static string Error_UnknownError_FriendlyName {
            get {
                return ResourceManager.GetString("Error_UnknownError_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gets the secret..
        /// </summary>
        public static string GetKeyVaultSecret_Description {
            get {
                return ResourceManager.GetString("GetKeyVaultSecret_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get secret.
        /// </summary>
        public static string GetKeyVaultSecret_FriendlyName {
            get {
                return ResourceManager.GetString("GetKeyVaultSecret_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name of the secret..
        /// </summary>
        public static string GetKeyVaultSecret_SecretName_Description {
            get {
                return ResourceManager.GetString("GetKeyVaultSecret_SecretName_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Secret name.
        /// </summary>
        public static string GetKeyVaultSecret_SecretName_FriendlyName {
            get {
                return ResourceManager.GetString("GetKeyVaultSecret_SecretName_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value of the secret..
        /// </summary>
        public static string GetKeyVaultSecret_SecretValue_Description {
            get {
                return ResourceManager.GetString("GetKeyVaultSecret_SecretValue_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Secret value.
        /// </summary>
        public static string GetKeyVaultSecret_SecretValue_FriendlyName {
            get {
                return ResourceManager.GetString("GetKeyVaultSecret_SecretValue_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get the secret..
        /// </summary>
        public static string GetKeyVaultSecret_Summary {
            get {
                return ResourceManager.GetString("GetKeyVaultSecret_Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The URL of the vault..
        /// </summary>
        public static string GetKeyVaultSecret_VaultUrl_Description {
            get {
                return ResourceManager.GetString("GetKeyVaultSecret_VaultUrl_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vault URL.
        /// </summary>
        public static string GetKeyVaultSecret_VaultUrl_FriendlyName {
            get {
                return ResourceManager.GetString("GetKeyVaultSecret_VaultUrl_FriendlyName", resourceCulture);
            }
        }
    }
}
