//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PowerAutomate.Desktop.Modules.RabbitMQ.Actions.Properties {
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PowerAutomate.Desktop.Modules.RabbitMQ.Actions.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Confirm successful processing of a delivery..
        /// </summary>
        public static string AcknowledgeMessage_Description {
            get {
                return ResourceManager.GetString("AcknowledgeMessage_Description", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Acknowledge RabbitMQ message.
        /// </summary>
        public static string AcknowledgeMessage_FriendlyName {
            get {
                return ResourceManager.GetString("AcknowledgeMessage_FriendlyName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Unsettled RabbitMQ message to acknowledge..
        /// </summary>
        public static string AcknowledgeMessage_Message_Description {
            get {
                return ResourceManager.GetString("AcknowledgeMessage_Message_Description", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        public static string AcknowledgeMessage_Message_FriendlyName {
            get {
                return ResourceManager.GetString("AcknowledgeMessage_Message_FriendlyName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Acknowledge a received message..
        /// </summary>
        public static string AcknowledgeMessage_Summary {
            get {
                return ResourceManager.GetString("AcknowledgeMessage_Summary", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to RabbitMQ connection to close..
        /// </summary>
        public static string CloseRabbitMq_Connection_Description {
            get {
                return ResourceManager.GetString("CloseRabbitMq_Connection_Description", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Connection.
        /// </summary>
        public static string CloseRabbitMq_Connection_FriendlyName {
            get {
                return ResourceManager.GetString("CloseRabbitMq_Connection_FriendlyName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Release a RabbitMQ connection and channel..
        /// </summary>
        public static string CloseRabbitMq_Description {
            get {
                return ResourceManager.GetString("CloseRabbitMq_Description", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Close RabbitMQ connection.
        /// </summary>
        public static string CloseRabbitMq_FriendlyName {
            get {
                return ResourceManager.GetString("CloseRabbitMq_FriendlyName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Close the RabbitMQ connection..
        /// </summary>
        public static string CloseRabbitMq_Summary {
            get {
                return ResourceManager.GetString("CloseRabbitMq_Summary", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Absolute amqp or amqps URI of the broker..
        /// </summary>
        public static string ConnectRabbitMq_Address_Description {
            get {
                return ResourceManager.GetString("ConnectRabbitMq_Address_Description", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Broker address.
        /// </summary>
        public static string ConnectRabbitMq_Address_FriendlyName {
            get {
                return ResourceManager.GetString("ConnectRabbitMq_Address_FriendlyName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Connection used by RabbitMQ actions..
        /// </summary>
        public static string ConnectRabbitMq_Connection_Description {
            get {
                return ResourceManager.GetString("ConnectRabbitMq_Connection_Description", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Connection.
        /// </summary>
        public static string ConnectRabbitMq_Connection_FriendlyName {
            get {
                return ResourceManager.GetString("ConnectRabbitMq_Connection_FriendlyName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Open a connection to a RabbitMQ broker..
        /// </summary>
        public static string ConnectRabbitMq_Description {
            get {
                return ResourceManager.GetString("ConnectRabbitMq_Description", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Connect to RabbitMQ.
        /// </summary>
        public static string ConnectRabbitMq_FriendlyName {
            get {
                return ResourceManager.GetString("ConnectRabbitMq_FriendlyName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Open a RabbitMQ connection..
        /// </summary>
        public static string ConnectRabbitMq_Summary {
            get {
                return ResourceManager.GetString("ConnectRabbitMq_Summary", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The broker rejected the operation or the connection failed..
        /// </summary>
        public static string Error_BrokerError_Description {
            get {
                return ResourceManager.GetString("Error_BrokerError_Description", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to RabbitMQ broker error.
        /// </summary>
        public static string Error_BrokerError_FriendlyName {
            get {
                return ResourceManager.GetString("Error_BrokerError_FriendlyName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The RabbitMQ session has already been closed..
        /// </summary>
        public static string Error_ClosedConnectionError_Description {
            get {
                return ResourceManager.GetString("Error_ClosedConnectionError_Description", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Connection closed.
        /// </summary>
        public static string Error_ClosedConnectionError_FriendlyName {
            get {
                return ResourceManager.GetString("Error_ClosedConnectionError_FriendlyName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to A required URI, session, queue, routing key, or message is invalid..
        /// </summary>
        public static string Error_InvalidArgumentError_Description {
            get {
                return ResourceManager.GetString("Error_InvalidArgumentError_Description", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Invalid input.
        /// </summary>
        public static string Error_InvalidArgumentError_FriendlyName {
            get {
                return ResourceManager.GetString("Error_InvalidArgumentError_FriendlyName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to This message has already been acknowledged or rejected..
        /// </summary>
        public static string Error_MessageSettledError_Description {
            get {
                return ResourceManager.GetString("Error_MessageSettledError_Description", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Message already settled.
        /// </summary>
        public static string Error_MessageSettledError_FriendlyName {
            get {
                return ResourceManager.GetString("Error_MessageSettledError_FriendlyName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to UTF-8 text to publish; empty text is allowed..
        /// </summary>
        public static string PublishMessage_Body_Description {
            get {
                return ResourceManager.GetString("PublishMessage_Body_Description", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Message body.
        /// </summary>
        public static string PublishMessage_Body_FriendlyName {
            get {
                return ResourceManager.GetString("PublishMessage_Body_FriendlyName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to An open RabbitMQ connection..
        /// </summary>
        public static string PublishMessage_Connection_Description {
            get {
                return ResourceManager.GetString("PublishMessage_Connection_Description", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Connection.
        /// </summary>
        public static string PublishMessage_Connection_FriendlyName {
            get {
                return ResourceManager.GetString("PublishMessage_Connection_FriendlyName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Publish a UTF-8 message and await broker confirmation..
        /// </summary>
        public static string PublishMessage_Description {
            get {
                return ResourceManager.GetString("PublishMessage_Description", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Exchange name; empty means the default exchange..
        /// </summary>
        public static string PublishMessage_Exchange_Description {
            get {
                return ResourceManager.GetString("PublishMessage_Exchange_Description", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Exchange.
        /// </summary>
        public static string PublishMessage_Exchange_FriendlyName {
            get {
                return ResourceManager.GetString("PublishMessage_Exchange_FriendlyName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Publish RabbitMQ message.
        /// </summary>
        public static string PublishMessage_FriendlyName {
            get {
                return ResourceManager.GetString("PublishMessage_FriendlyName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Mark the message persistent for durable queues..
        /// </summary>
        public static string PublishMessage_IsPersistent_Description {
            get {
                return ResourceManager.GetString("PublishMessage_IsPersistent_Description", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Persistent.
        /// </summary>
        public static string PublishMessage_IsPersistent_FriendlyName {
            get {
                return ResourceManager.GetString("PublishMessage_IsPersistent_FriendlyName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Routing key or queue name when using the default exchange..
        /// </summary>
        public static string PublishMessage_RoutingKey_Description {
            get {
                return ResourceManager.GetString("PublishMessage_RoutingKey_Description", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Routing key.
        /// </summary>
        public static string PublishMessage_RoutingKey_FriendlyName {
            get {
                return ResourceManager.GetString("PublishMessage_RoutingKey_FriendlyName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Publish a message to an exchange..
        /// </summary>
        public static string PublishMessage_Summary {
            get {
                return ResourceManager.GetString("PublishMessage_Summary", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Publish and receive RabbitMQ messages..
        /// </summary>
        public static string RabbitMQ_Description {
            get {
                return ResourceManager.GetString("RabbitMQ_Description", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to RabbitMQ.
        /// </summary>
        public static string RabbitMQ_FriendlyName {
            get {
                return ResourceManager.GetString("RabbitMQ_FriendlyName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to RabbitMQ connection.
        /// </summary>
        public static string RabbitMqConnection_FriendlyName {
            get {
                return ResourceManager.GetString("RabbitMqConnection_FriendlyName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to RabbitMQ connections.
        /// </summary>
        public static string RabbitMqConnection_FriendlyNamePlural {
            get {
                return ResourceManager.GetString("RabbitMqConnection_FriendlyNamePlural", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to RabbitMQ message.
        /// </summary>
        public static string RabbitMqMessage_FriendlyName {
            get {
                return ResourceManager.GetString("RabbitMqMessage_FriendlyName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to RabbitMQ messages.
        /// </summary>
        public static string RabbitMqMessage_FriendlyNamePlural {
            get {
                return ResourceManager.GetString("RabbitMqMessage_FriendlyNamePlural", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to An open RabbitMQ connection..
        /// </summary>
        public static string ReceiveMessage_Connection_Description {
            get {
                return ResourceManager.GetString("ReceiveMessage_Connection_Description", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Connection.
        /// </summary>
        public static string ReceiveMessage_Connection_FriendlyName {
            get {
                return ResourceManager.GetString("ReceiveMessage_Connection_FriendlyName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Poll a queue once without acknowledging the delivery..
        /// </summary>
        public static string ReceiveMessage_Description {
            get {
                return ResourceManager.GetString("ReceiveMessage_Description", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Get RabbitMQ message.
        /// </summary>
        public static string ReceiveMessage_FriendlyName {
            get {
                return ResourceManager.GetString("ReceiveMessage_FriendlyName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Whether a message was available..
        /// </summary>
        public static string ReceiveMessage_IsFound_Description {
            get {
                return ResourceManager.GetString("ReceiveMessage_IsFound_Description", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Found.
        /// </summary>
        public static string ReceiveMessage_IsFound_FriendlyName {
            get {
                return ResourceManager.GetString("ReceiveMessage_IsFound_FriendlyName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Unacknowledged delivery to process and settle..
        /// </summary>
        public static string ReceiveMessage_Message_Description {
            get {
                return ResourceManager.GetString("ReceiveMessage_Message_Description", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        public static string ReceiveMessage_Message_FriendlyName {
            get {
                return ResourceManager.GetString("ReceiveMessage_Message_FriendlyName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Name of an existing queue to poll once..
        /// </summary>
        public static string ReceiveMessage_Queue_Description {
            get {
                return ResourceManager.GetString("ReceiveMessage_Queue_Description", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Queue.
        /// </summary>
        public static string ReceiveMessage_Queue_FriendlyName {
            get {
                return ResourceManager.GetString("ReceiveMessage_Queue_FriendlyName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Get one message from a queue..
        /// </summary>
        public static string ReceiveMessage_Summary {
            get {
                return ResourceManager.GetString("ReceiveMessage_Summary", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Return the delivery to the queue; defaults to false..
        /// </summary>
        public static string RejectMessage_AllowRequeue_Description {
            get {
                return ResourceManager.GetString("RejectMessage_AllowRequeue_Description", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Requeue.
        /// </summary>
        public static string RejectMessage_AllowRequeue_FriendlyName {
            get {
                return ResourceManager.GetString("RejectMessage_AllowRequeue_FriendlyName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Negatively acknowledge a delivery, optionally requeuing it..
        /// </summary>
        public static string RejectMessage_Description {
            get {
                return ResourceManager.GetString("RejectMessage_Description", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Reject RabbitMQ message.
        /// </summary>
        public static string RejectMessage_FriendlyName {
            get {
                return ResourceManager.GetString("RejectMessage_FriendlyName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Unsettled RabbitMQ message to reject..
        /// </summary>
        public static string RejectMessage_Message_Description {
            get {
                return ResourceManager.GetString("RejectMessage_Message_Description", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        public static string RejectMessage_Message_FriendlyName {
            get {
                return ResourceManager.GetString("RejectMessage_Message_FriendlyName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Reject a received message..
        /// </summary>
        public static string RejectMessage_Summary {
            get {
                return ResourceManager.GetString("RejectMessage_Summary", resourceCulture);
            }
        }
    }
}
