//-------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------

namespace PowerAutomate.Desktop.Modules.GitHub.Copilot.Actions.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PowerAutomate.Desktop.Modules.GitHub.Copilot.Actions.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indicates that there was a problem when launching or executing the Copilot CLI..
        /// </summary>
        public static string Error_UnknownError_Description {
            get {
                return ResourceManager.GetString("Error_UnknownError_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation failed.
        /// </summary>
        public static string Error_UnknownError_FriendlyName {
            get {
                return ResourceManager.GetString("Error_UnknownError_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Perform operations using the GitHub Copilot CLI..
        /// </summary>
        public static string GitHubCopilot_Description {
            get {
                return ResourceManager.GetString("GitHubCopilot_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GitHub Copilot CLI.
        /// </summary>
        public static string GitHubCopilot_FriendlyName {
            get {
                return ResourceManager.GetString("GitHubCopilot_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Not set).
        /// </summary>
        public static string CopilotSwitch_Unset_FriendlyName {
            get {
                return ResourceManager.GetString("CopilotSwitch_Unset_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to True.
        /// </summary>
        public static string CopilotSwitch_Yes_FriendlyName {
            get {
                return ResourceManager.GetString("CopilotSwitch_Yes_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to False.
        /// </summary>
        public static string CopilotSwitch_No_FriendlyName {
            get {
                return ResourceManager.GetString("CopilotSwitch_No_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Low.
        /// </summary>
        public static string CopilotEffortLevel_Low_FriendlyName {
            get {
                return ResourceManager.GetString("CopilotEffortLevel_Low_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medium.
        /// </summary>
        public static string CopilotEffortLevel_Medium_FriendlyName {
            get {
                return ResourceManager.GetString("CopilotEffortLevel_Medium_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High.
        /// </summary>
        public static string CopilotEffortLevel_High_FriendlyName {
            get {
                return ResourceManager.GetString("CopilotEffortLevel_High_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        public static string CopilotLogLevel_None_FriendlyName {
            get {
                return ResourceManager.GetString("CopilotLogLevel_None_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string CopilotLogLevel_Error_FriendlyName {
            get {
                return ResourceManager.GetString("CopilotLogLevel_Error_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        public static string CopilotLogLevel_Warning_FriendlyName {
            get {
                return ResourceManager.GetString("CopilotLogLevel_Warning_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info.
        /// </summary>
        public static string CopilotLogLevel_Info_FriendlyName {
            get {
                return ResourceManager.GetString("CopilotLogLevel_Info_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debug.
        /// </summary>
        public static string CopilotLogLevel_Debug_FriendlyName {
            get {
                return ResourceManager.GetString("CopilotLogLevel_Debug_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        public static string CopilotLogLevel_All_FriendlyName {
            get {
                return ResourceManager.GetString("CopilotLogLevel_All_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default.
        /// </summary>
        public static string CopilotLogLevel_Default_FriendlyName {
            get {
                return ResourceManager.GetString("CopilotLogLevel_Default_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interactive.
        /// </summary>
        public static string CopilotMode_Interactive_FriendlyName {
            get {
                return ResourceManager.GetString("CopilotMode_Interactive_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plan.
        /// </summary>
        public static string CopilotMode_Plan_FriendlyName {
            get {
                return ResourceManager.GetString("CopilotMode_Plan_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autopilot.
        /// </summary>
        public static string CopilotMode_Autopilot_FriendlyName {
            get {
                return ResourceManager.GetString("CopilotMode_Autopilot_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text.
        /// </summary>
        public static string CopilotOutputFormat_Text_FriendlyName {
            get {
                return ResourceManager.GetString("CopilotOutputFormat_Text_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JSON.
        /// </summary>
        public static string CopilotOutputFormat_Json_FriendlyName {
            get {
                return ResourceManager.GetString("CopilotOutputFormat_Json_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On.
        /// </summary>
        public static string CopilotStreamMode_On_FriendlyName {
            get {
                return ResourceManager.GetString("CopilotStreamMode_On_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Off.
        /// </summary>
        public static string CopilotStreamMode_Off_FriendlyName {
            get {
                return ResourceManager.GetString("CopilotStreamMode_Off_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The MCP configuration as a JSON string (--additional-mcp-config)..
        /// </summary>
        public static string LaunchCopilotCli_AdditionalMcpConfig_Description {
            get {
                return ResourceManager.GetString("LaunchCopilotCli_AdditionalMcpConfig_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additional MCP config.
        /// </summary>
        public static string LaunchCopilotCli_AdditionalMcpConfig_FriendlyName {
            get {
                return ResourceManager.GetString("LaunchCopilotCli_AdditionalMcpConfig_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comma-separated list of directories to add to the context. Each value becomes a separate --add-dir flag..
        /// </summary>
        public static string LaunchCopilotCli_AddDir_Description {
            get {
                return ResourceManager.GetString("LaunchCopilotCli_AddDir_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add directory.
        /// </summary>
        public static string LaunchCopilotCli_AddDir_FriendlyName {
            get {
                return ResourceManager.GetString("LaunchCopilotCli_AddDir_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comma-separated list of GitHub MCP tools to add..
        /// </summary>
        public static string LaunchCopilotCli_AddGithubMcpTool_Description {
            get {
                return ResourceManager.GetString("LaunchCopilotCli_AddGithubMcpTool_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add GitHub MCP tool.
        /// </summary>
        public static string LaunchCopilotCli_AddGithubMcpTool_FriendlyName {
            get {
                return ResourceManager.GetString("LaunchCopilotCli_AddGithubMcpTool_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comma-separated list of GitHub MCP toolsets to add..
        /// </summary>
        public static string LaunchCopilotCli_AddGithubMcpToolset_Description {
            get {
                return ResourceManager.GetString("LaunchCopilotCli_AddGithubMcpToolset_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add GitHub MCP toolset.
        /// </summary>
        public static string LaunchCopilotCli_AddGithubMcpToolset_FriendlyName {
            get {
                return ResourceManager.GetString("LaunchCopilotCli_AddGithubMcpToolset_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The agent to use for the session (--agent)..
        /// </summary>
        public static string LaunchCopilotCli_Agent_Description {
            get {
                return ResourceManager.GetString("LaunchCopilotCli_Agent_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agent.
        /// </summary>
        public static string LaunchCopilotCli_Agent_FriendlyName {
            get {
                return ResourceManager.GetString("LaunchCopilotCli_Agent_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow access to all file system paths without confirmation (--allow-all-paths)..
        /// </summary>
        public static string LaunchCopilotCli_AllowAllPaths_Description {
            get {
                return ResourceManager.GetString("LaunchCopilotCli_AllowAllPaths_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow all paths.
        /// </summary>
        public static string LaunchCopilotCli_AllowAllPaths_FriendlyName {
            get {
                return ResourceManager.GetString("LaunchCopilotCli_AllowAllPaths_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow all tools to be used without confirmation (--allow-all-tools)..
        /// </summary>
        public static string LaunchCopilotCli_AllowAllTools_Description {
            get {
                return ResourceManager.GetString("LaunchCopilotCli_AllowAllTools_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow all tools.
        /// </summary>
        public static string LaunchCopilotCli_AllowAllTools_FriendlyName {
            get {
                return ResourceManager.GetString("LaunchCopilotCli_AllowAllTools_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow all URLs to be accessed without confirmation (--allow-all-urls)..
        /// </summary>
        public static string LaunchCopilotCli_AllowAllUrls_Description {
            get {
                return ResourceManager.GetString("LaunchCopilotCli_AllowAllUrls_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow all URLs.
        /// </summary>
        public static string LaunchCopilotCli_AllowAllUrls_FriendlyName {
            get {
                return ResourceManager.GetString("LaunchCopilotCli_AllowAllUrls_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow all tools, paths, and URLs without confirmation (--allow-all)..
        /// </summary>
        public static string LaunchCopilotCli_AllowAll_Description {
            get {
                return ResourceManager.GetString("LaunchCopilotCli_AllowAll_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow all.
        /// </summary>
        public static string LaunchCopilotCli_AllowAll_FriendlyName {
            get {
                return ResourceManager.GetString("LaunchCopilotCli_AllowAll_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comma-separated list of tools to allow..
        /// </summary>
        public static string LaunchCopilotCli_AllowTool_Description {
            get {
                return ResourceManager.GetString("LaunchCopilotCli_AllowTool_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow tool.
        /// </summary>
        public static string LaunchCopilotCli_AllowTool_FriendlyName {
            get {
                return ResourceManager.GetString("LaunchCopilotCli_AllowTool_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comma-separated list of URLs to allow..
        /// </summary>
        public static string LaunchCopilotCli_AllowUrl_Description {
            get {
                return ResourceManager.GetString("LaunchCopilotCli_AllowUrl_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow URL.
        /// </summary>
        public static string LaunchCopilotCli_AllowUrl_FriendlyName {
            get {
                return ResourceManager.GetString("LaunchCopilotCli_AllowUrl_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run in autopilot mode, executing tasks autonomously (--autopilot)..
        /// </summary>
        public static string LaunchCopilotCli_Autopilot_Description {
            get {
                return ResourceManager.GetString("LaunchCopilotCli_Autopilot_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autopilot.
        /// </summary>
        public static string LaunchCopilotCli_Autopilot_FriendlyName {
            get {
                return ResourceManager.GetString("LaunchCopilotCli_Autopilot_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comma-separated list of tools to make available (--available-tools)..
        /// </summary>
        public static string LaunchCopilotCli_AvailableTools_Description {
            get {
                return ResourceManager.GetString("LaunchCopilotCli_AvailableTools_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available tools.
        /// </summary>
        public static string LaunchCopilotCli_AvailableTools_FriendlyName {
            get {
                return ResourceManager.GetString("LaunchCopilotCli_AvailableTools_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show the Copilot banner on startup (--banner)..
        /// </summary>
        public static string LaunchCopilotCli_Banner_Description {
            get {
                return ResourceManager.GetString("LaunchCopilotCli_Banner_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Banner.
        /// </summary>
        public static string LaunchCopilotCli_Banner_FriendlyName {
            get {
                return ResourceManager.GetString("LaunchCopilotCli_Banner_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source the bash environment before running commands (--bash-env)..
        /// </summary>
        public static string LaunchCopilotCli_BashEnv_Description {
            get {
                return ResourceManager.GetString("LaunchCopilotCli_BashEnv_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bash env.
        /// </summary>
        public static string LaunchCopilotCli_BashEnv_FriendlyName {
            get {
                return ResourceManager.GetString("LaunchCopilotCli_BashEnv_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect to a remote session by session ID (--connect)..
        /// </summary>
        public static string LaunchCopilotCli_Connect_Description {
            get {
                return ResourceManager.GetString("LaunchCopilotCli_Connect_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect.
        /// </summary>
        public static string LaunchCopilotCli_Connect_FriendlyName {
            get {
                return ResourceManager.GetString("LaunchCopilotCli_Connect_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resume the most recent session (--continue)..
        /// </summary>
        public static string LaunchCopilotCli_Continue_Description {
            get {
                return ResourceManager.GetString("LaunchCopilotCli_Continue_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue.
        /// </summary>
        public static string LaunchCopilotCli_Continue_FriendlyName {
            get {
                return ResourceManager.GetString("LaunchCopilotCli_Continue_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Launches the GitHub Copilot CLI with the specified options..
        /// </summary>
        public static string LaunchCopilotCli_Description {
            get {
                return ResourceManager.GetString("LaunchCopilotCli_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comma-separated list of tools to deny..
        /// </summary>
        public static string LaunchCopilotCli_DenyTool_Description {
            get {
                return ResourceManager.GetString("LaunchCopilotCli_DenyTool_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deny tool.
        /// </summary>
        public static string LaunchCopilotCli_DenyTool_FriendlyName {
            get {
                return ResourceManager.GetString("LaunchCopilotCli_DenyTool_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comma-separated list of URLs to deny..
        /// </summary>
        public static string LaunchCopilotCli_DenyUrl_Description {
            get {
                return ResourceManager.GetString("LaunchCopilotCli_DenyUrl_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deny URL.
        /// </summary>
        public static string LaunchCopilotCli_DenyUrl_FriendlyName {
            get {
                return ResourceManager.GetString("LaunchCopilotCli_DenyUrl_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable all built-in MCP servers (--disable-builtin-mcps)..
        /// </summary>
        public static string LaunchCopilotCli_DisableBuiltinMcps_Description {
            get {
                return ResourceManager.GetString("LaunchCopilotCli_DisableBuiltinMcps_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable built-in MCPs.
        /// </summary>
        public static string LaunchCopilotCli_DisableBuiltinMcps_FriendlyName {
            get {
                return ResourceManager.GetString("LaunchCopilotCli_DisableBuiltinMcps_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comma-separated list of MCP server names to disable..
        /// </summary>
        public static string LaunchCopilotCli_DisableMcpServer_Description {
            get {
                return ResourceManager.GetString("LaunchCopilotCli_DisableMcpServer_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable MCP server.
        /// </summary>
        public static string LaunchCopilotCli_DisableMcpServer_FriendlyName {
            get {
                return ResourceManager.GetString("LaunchCopilotCli_DisableMcpServer_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prevent Copilot from using the system temp directory (--disallow-temp-dir)..
        /// </summary>
        public static string LaunchCopilotCli_DisallowTempDir_Description {
            get {
                return ResourceManager.GetString("LaunchCopilotCli_DisallowTempDir_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disallow temp directory.
        /// </summary>
        public static string LaunchCopilotCli_DisallowTempDir_FriendlyName {
            get {
                return ResourceManager.GetString("LaunchCopilotCli_DisallowTempDir_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The reasoning effort level: Low, Medium, or High (--effort)..
        /// </summary>
        public static string LaunchCopilotCli_Effort_Description {
            get {
                return ResourceManager.GetString("LaunchCopilotCli_Effort_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Effort level.
        /// </summary>
        public static string LaunchCopilotCli_Effort_FriendlyName {
            get {
                return ResourceManager.GetString("LaunchCopilotCli_Effort_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable all available GitHub MCP tools (--enable-all-github-mcp-tools)..
        /// </summary>
        public static string LaunchCopilotCli_EnableAllGithubMcpTools_Description {
            get {
                return ResourceManager.GetString("LaunchCopilotCli_EnableAllGithubMcpTools_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable all GitHub MCP tools.
        /// </summary>
        public static string LaunchCopilotCli_EnableAllGithubMcpTools_FriendlyName {
            get {
                return ResourceManager.GetString("LaunchCopilotCli_EnableAllGithubMcpTools_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable reasoning summaries in the output (--enable-reasoning-summaries)..
        /// </summary>
        public static string LaunchCopilotCli_EnableReasoningSummaries_Description {
            get {
                return ResourceManager.GetString("LaunchCopilotCli_EnableReasoningSummaries_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable reasoning summaries.
        /// </summary>
        public static string LaunchCopilotCli_EnableReasoningSummaries_FriendlyName {
            get {
                return ResourceManager.GetString("LaunchCopilotCli_EnableReasoningSummaries_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable experimental features (--experimental)..
        /// </summary>
        public static string LaunchCopilotCli_Experimental_Description {
            get {
                return ResourceManager.GetString("LaunchCopilotCli_Experimental_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Experimental.
        /// </summary>
        public static string LaunchCopilotCli_Experimental_FriendlyName {
            get {
                return ResourceManager.GetString("LaunchCopilotCli_Experimental_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full path to the copilot executable..
        /// </summary>
        public static string LaunchCopilotCli_ExecutablePath_Description {
            get {
                return ResourceManager.GetString("LaunchCopilotCli_ExecutablePath_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Executable path.
        /// </summary>
        public static string LaunchCopilotCli_ExecutablePath_FriendlyName {
            get {
                return ResourceManager.GetString("LaunchCopilotCli_ExecutablePath_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The exit code returned by the copilot process..
        /// </summary>
        public static string LaunchCopilotCli_ExitCode_Description {
            get {
                return ResourceManager.GetString("LaunchCopilotCli_ExitCode_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit code.
        /// </summary>
        public static string LaunchCopilotCli_ExitCode_FriendlyName {
            get {
                return ResourceManager.GetString("LaunchCopilotCli_ExitCode_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comma-separated list of tools to exclude (--excluded-tools)..
        /// </summary>
        public static string LaunchCopilotCli_ExcludedTools_Description {
            get {
                return ResourceManager.GetString("LaunchCopilotCli_ExcludedTools_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excluded tools.
        /// </summary>
        public static string LaunchCopilotCli_ExcludedTools_FriendlyName {
            get {
                return ResourceManager.GetString("LaunchCopilotCli_ExcludedTools_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Launch Copilot CLI.
        /// </summary>
        public static string LaunchCopilotCli_FriendlyName {
            get {
                return ResourceManager.GetString("LaunchCopilotCli_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start an interactive session and automatically send this prompt (--interactive / -i)..
        /// </summary>
        public static string LaunchCopilotCli_InteractivePrompt_Description {
            get {
                return ResourceManager.GetString("LaunchCopilotCli_InteractivePrompt_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interactive prompt.
        /// </summary>
        public static string LaunchCopilotCli_InteractivePrompt_FriendlyName {
            get {
                return ResourceManager.GetString("LaunchCopilotCli_InteractivePrompt_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directory where log files are written (--log-dir)..
        /// </summary>
        public static string LaunchCopilotCli_LogDir_Description {
            get {
                return ResourceManager.GetString("LaunchCopilotCli_LogDir_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log directory.
        /// </summary>
        public static string LaunchCopilotCli_LogDir_FriendlyName {
            get {
                return ResourceManager.GetString("LaunchCopilotCli_LogDir_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The logging verbosity level (--log-level)..
        /// </summary>
        public static string LaunchCopilotCli_LogLevel_Description {
            get {
                return ResourceManager.GetString("LaunchCopilotCli_LogLevel_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log level.
        /// </summary>
        public static string LaunchCopilotCli_LogLevel_FriendlyName {
            get {
                return ResourceManager.GetString("LaunchCopilotCli_LogLevel_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum number of automatic continuation steps in autopilot mode (--max-autopilot-continues)..
        /// </summary>
        public static string LaunchCopilotCli_MaxAutopilotContinues_Description {
            get {
                return ResourceManager.GetString("LaunchCopilotCli_MaxAutopilotContinues_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max autopilot continues.
        /// </summary>
        public static string LaunchCopilotCli_MaxAutopilotContinues_FriendlyName {
            get {
                return ResourceManager.GetString("LaunchCopilotCli_MaxAutopilotContinues_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The AI model to use for the session (--model)..
        /// </summary>
        public static string LaunchCopilotCli_Model_Description {
            get {
                return ResourceManager.GetString("LaunchCopilotCli_Model_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model.
        /// </summary>
        public static string LaunchCopilotCli_Model_FriendlyName {
            get {
                return ResourceManager.GetString("LaunchCopilotCli_Model_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set the operating mode: Interactive, Plan, or Autopilot (--mode)..
        /// </summary>
        public static string LaunchCopilotCli_Mode_Description {
            get {
                return ResourceManager.GetString("LaunchCopilotCli_Mode_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mode.
        /// </summary>
        public static string LaunchCopilotCli_Mode_FriendlyName {
            get {
                return ResourceManager.GetString("LaunchCopilotCli_Mode_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable mouse support in the terminal UI (--mouse)..
        /// </summary>
        public static string LaunchCopilotCli_Mouse_Description {
            get {
                return ResourceManager.GetString("LaunchCopilotCli_Mouse_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mouse.
        /// </summary>
        public static string LaunchCopilotCli_Mouse_FriendlyName {
            get {
                return ResourceManager.GetString("LaunchCopilotCli_Mouse_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable automatic updates of the Copilot CLI (--no-auto-update)..
        /// </summary>
        public static string LaunchCopilotCli_NoAutoUpdate_Description {
            get {
                return ResourceManager.GetString("LaunchCopilotCli_NoAutoUpdate_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No auto update.
        /// </summary>
        public static string LaunchCopilotCli_NoAutoUpdate_FriendlyName {
            get {
                return ResourceManager.GetString("LaunchCopilotCli_NoAutoUpdate_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suppress interactive confirmation prompts (--no-ask-user)..
        /// </summary>
        public static string LaunchCopilotCli_NoAskUser_Description {
            get {
                return ResourceManager.GetString("LaunchCopilotCli_NoAskUser_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No ask user.
        /// </summary>
        public static string LaunchCopilotCli_NoAskUser_FriendlyName {
            get {
                return ResourceManager.GetString("LaunchCopilotCli_NoAskUser_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable colored output (--no-color)..
        /// </summary>
        public static string LaunchCopilotCli_NoColor_Description {
            get {
                return ResourceManager.GetString("LaunchCopilotCli_NoColor_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No color.
        /// </summary>
        public static string LaunchCopilotCli_NoColor_FriendlyName {
            get {
                return ResourceManager.GetString("LaunchCopilotCli_NoColor_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignore any custom instruction files in the repository (--no-custom-instructions)..
        /// </summary>
        public static string LaunchCopilotCli_NoCustomInstructions_Description {
            get {
                return ResourceManager.GetString("LaunchCopilotCli_NoCustomInstructions_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No custom instructions.
        /// </summary>
        public static string LaunchCopilotCli_NoCustomInstructions_FriendlyName {
            get {
                return ResourceManager.GetString("LaunchCopilotCli_NoCustomInstructions_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The output format: Text or Json (--output-format)..
        /// </summary>
        public static string LaunchCopilotCli_OutputFormat_Description {
            get {
                return ResourceManager.GetString("LaunchCopilotCli_OutputFormat_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output format.
        /// </summary>
        public static string LaunchCopilotCli_OutputFormat_FriendlyName {
            get {
                return ResourceManager.GetString("LaunchCopilotCli_OutputFormat_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run in plan mode, generating a plan before executing (--plan)..
        /// </summary>
        public static string LaunchCopilotCli_Plan_Description {
            get {
                return ResourceManager.GetString("LaunchCopilotCli_Plan_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plan.
        /// </summary>
        public static string LaunchCopilotCli_Plan_FriendlyName {
            get {
                return ResourceManager.GetString("LaunchCopilotCli_Plan_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show diffs in plain text format (--plain-diff)..
        /// </summary>
        public static string LaunchCopilotCli_PlainDiff_Description {
            get {
                return ResourceManager.GetString("LaunchCopilotCli_PlainDiff_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plain diff.
        /// </summary>
        public static string LaunchCopilotCli_PlainDiff_FriendlyName {
            get {
                return ResourceManager.GetString("LaunchCopilotCli_PlainDiff_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comma-separated list of directories containing plugins..
        /// </summary>
        public static string LaunchCopilotCli_PluginDir_Description {
            get {
                return ResourceManager.GetString("LaunchCopilotCli_PluginDir_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plugin directory.
        /// </summary>
        public static string LaunchCopilotCli_PluginDir_FriendlyName {
            get {
                return ResourceManager.GetString("LaunchCopilotCli_PluginDir_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Execute a prompt programmatically and exit (--prompt / -p)..
        /// </summary>
        public static string LaunchCopilotCli_Prompt_Description {
            get {
                return ResourceManager.GetString("LaunchCopilotCli_Prompt_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prompt.
        /// </summary>
        public static string LaunchCopilotCli_Prompt_FriendlyName {
            get {
                return ResourceManager.GetString("LaunchCopilotCli_Prompt_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use a remote session (--remote)..
        /// </summary>
        public static string LaunchCopilotCli_Remote_Description {
            get {
                return ResourceManager.GetString("LaunchCopilotCli_Remote_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remote.
        /// </summary>
        public static string LaunchCopilotCli_Remote_FriendlyName {
            get {
                return ResourceManager.GetString("LaunchCopilotCli_Remote_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resume a previous session by ID or name (--resume)..
        /// </summary>
        public static string LaunchCopilotCli_Resume_Description {
            get {
                return ResourceManager.GetString("LaunchCopilotCli_Resume_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resume.
        /// </summary>
        public static string LaunchCopilotCli_Resume_FriendlyName {
            get {
                return ResourceManager.GetString("LaunchCopilotCli_Resume_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable screen reader accessibility mode (--screen-reader)..
        /// </summary>
        public static string LaunchCopilotCli_ScreenReader_Description {
            get {
                return ResourceManager.GetString("LaunchCopilotCli_ScreenReader_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Screen reader.
        /// </summary>
        public static string LaunchCopilotCli_ScreenReader_FriendlyName {
            get {
                return ResourceManager.GetString("LaunchCopilotCli_ScreenReader_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comma-separated list of environment variable names to treat as secrets..
        /// </summary>
        public static string LaunchCopilotCli_SecretEnvVars_Description {
            get {
                return ResourceManager.GetString("LaunchCopilotCli_SecretEnvVars_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Secret environment variables.
        /// </summary>
        public static string LaunchCopilotCli_SecretEnvVars_FriendlyName {
            get {
                return ResourceManager.GetString("LaunchCopilotCli_SecretEnvVars_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name for the session (--name / -n)..
        /// </summary>
        public static string LaunchCopilotCli_SessionName_Description {
            get {
                return ResourceManager.GetString("LaunchCopilotCli_SessionName_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Session name.
        /// </summary>
        public static string LaunchCopilotCli_SessionName_FriendlyName {
            get {
                return ResourceManager.GetString("LaunchCopilotCli_SessionName_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path for sharing the session output (--share)..
        /// </summary>
        public static string LaunchCopilotCli_Share_Description {
            get {
                return ResourceManager.GetString("LaunchCopilotCli_Share_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share path.
        /// </summary>
        public static string LaunchCopilotCli_Share_FriendlyName {
            get {
                return ResourceManager.GetString("LaunchCopilotCli_Share_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share the session output as a GitHub Gist (--share-gist)..
        /// </summary>
        public static string LaunchCopilotCli_ShareGist_Description {
            get {
                return ResourceManager.GetString("LaunchCopilotCli_ShareGist_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share gist.
        /// </summary>
        public static string LaunchCopilotCli_ShareGist_FriendlyName {
            get {
                return ResourceManager.GetString("LaunchCopilotCli_ShareGist_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suppress all non-essential output (--silent)..
        /// </summary>
        public static string LaunchCopilotCli_Silent_Description {
            get {
                return ResourceManager.GetString("LaunchCopilotCli_Silent_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Silent.
        /// </summary>
        public static string LaunchCopilotCli_Silent_FriendlyName {
            get {
                return ResourceManager.GetString("LaunchCopilotCli_Silent_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The text written to standard error (stderr) by the copilot process..
        /// </summary>
        public static string LaunchCopilotCli_StandardError_Description {
            get {
                return ResourceManager.GetString("LaunchCopilotCli_StandardError_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standard error.
        /// </summary>
        public static string LaunchCopilotCli_StandardError_FriendlyName {
            get {
                return ResourceManager.GetString("LaunchCopilotCli_StandardError_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The text written to standard output (stdout) by the copilot process..
        /// </summary>
        public static string LaunchCopilotCli_StandardOutput_Description {
            get {
                return ResourceManager.GetString("LaunchCopilotCli_StandardOutput_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standard output.
        /// </summary>
        public static string LaunchCopilotCli_StandardOutput_FriendlyName {
            get {
                return ResourceManager.GetString("LaunchCopilotCli_StandardOutput_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Control streaming output: On or Off (--stream)..
        /// </summary>
        public static string LaunchCopilotCli_Stream_Description {
            get {
                return ResourceManager.GetString("LaunchCopilotCli_Stream_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stream mode.
        /// </summary>
        public static string LaunchCopilotCli_Stream_FriendlyName {
            get {
                return ResourceManager.GetString("LaunchCopilotCli_Stream_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Launch the GitHub Copilot CLI..
        /// </summary>
        public static string LaunchCopilotCli_Summary {
            get {
                return ResourceManager.GetString("LaunchCopilotCli_Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Launch Copilot CLI in interactive mode..
        /// </summary>
        public static string LaunchCopilotCli_Interactive_Summary {
            get {
                return ResourceManager.GetString("LaunchCopilotCli_Interactive_Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Launch Copilot CLI in plan mode..
        /// </summary>
        public static string LaunchCopilotCli_Plan_Summary {
            get {
                return ResourceManager.GetString("LaunchCopilotCli_Plan_Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Launch Copilot CLI in autopilot mode..
        /// </summary>
        public static string LaunchCopilotCli_Autopilot_Summary {
            get {
                return ResourceManager.GetString("LaunchCopilotCli_Autopilot_Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The working directory for the copilot process..
        /// </summary>
        public static string LaunchCopilotCli_WorkingDirectory_Description {
            get {
                return ResourceManager.GetString("LaunchCopilotCli_WorkingDirectory_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Working directory.
        /// </summary>
        public static string LaunchCopilotCli_WorkingDirectory_FriendlyName {
            get {
                return ResourceManager.GetString("LaunchCopilotCli_WorkingDirectory_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced and miscellaneous settings..
        /// </summary>
        public static string Group_Advanced_Description {
            get {
                return ResourceManager.GetString("Group_Advanced_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced.
        /// </summary>
        public static string Group_Advanced_FriendlyName {
            get {
                return ResourceManager.GetString("Group_Advanced_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output format, logging, and display settings..
        /// </summary>
        public static string Group_Display_Description {
            get {
                return ResourceManager.GetString("Group_Display_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display &amp; Output.
        /// </summary>
        public static string Group_Display_FriendlyName {
            get {
                return ResourceManager.GetString("Group_Display_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General settings for the Copilot CLI execution..
        /// </summary>
        public static string Group_General_Description {
            get {
                return ResourceManager.GetString("Group_General_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        public static string Group_General_FriendlyName {
            get {
                return ResourceManager.GetString("Group_General_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model Context Protocol server, plugin, and directory settings..
        /// </summary>
        public static string Group_Mcp_Description {
            get {
                return ResourceManager.GetString("Group_Mcp_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MCP &amp; Plugins.
        /// </summary>
        public static string Group_Mcp_FriendlyName {
            get {
                return ResourceManager.GetString("Group_Mcp_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AI model and reasoning settings..
        /// </summary>
        public static string Group_Model_Description {
            get {
                return ResourceManager.GetString("Group_Model_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model.
        /// </summary>
        public static string Group_Model_FriendlyName {
            get {
                return ResourceManager.GetString("Group_Model_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operating mode and autopilot settings..
        /// </summary>
        public static string Group_Mode_Description {
            get {
                return ResourceManager.GetString("Group_Mode_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mode.
        /// </summary>
        public static string Group_Mode_FriendlyName {
            get {
                return ResourceManager.GetString("Group_Mode_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permission and access control settings for tools, paths, and URLs..
        /// </summary>
        public static string Group_Permissions_Description {
            get {
                return ResourceManager.GetString("Group_Permissions_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permissions.
        /// </summary>
        public static string Group_Permissions_FriendlyName {
            get {
                return ResourceManager.GetString("Group_Permissions_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Session management settings..
        /// </summary>
        public static string Group_Session_Description {
            get {
                return ResourceManager.GetString("Group_Session_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Session.
        /// </summary>
        public static string Group_Session_FriendlyName {
            get {
                return ResourceManager.GetString("Group_Session_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alias for --allow-all; skip all permission prompts (--yolo)..
        /// </summary>
        public static string LaunchCopilotCli_Yolo_Description {
            get {
                return ResourceManager.GetString("LaunchCopilotCli_Yolo_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yolo.
        /// </summary>
        public static string LaunchCopilotCli_Yolo_FriendlyName {
            get {
                return ResourceManager.GetString("LaunchCopilotCli_Yolo_FriendlyName", resourceCulture);
            }
        }
    }
}
