//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PowerAutomate.Desktop.Modules.CloudFlows.Actions.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PowerAutomate.Desktop.Modules.CloudFlows.Actions.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Perform operations related to Cloud Flows in Power Automate..
        /// </summary>
        public static string CloudFlows_Description {
            get {
                return ResourceManager.GetString("CloudFlows_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cloud Flows.
        /// </summary>
        public static string CloudFlows_FriendlyName {
            get {
                return ResourceManager.GetString("CloudFlows_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indicates that there was a problem when executing the operation..
        /// </summary>
        public static string Error_UnknownError_Description {
            get {
                return ResourceManager.GetString("Error_UnknownError_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation failed.
        /// </summary>
        public static string Error_UnknownError_FriendlyName {
            get {
                return ResourceManager.GetString("Error_UnknownError_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The access token..
        /// </summary>
        public static string RunFlow_AccessToken_Description {
            get {
                return ResourceManager.GetString("RunFlow_AccessToken_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access token.
        /// </summary>
        public static string RunFlow_AccessToken_FriendlyName {
            get {
                return ResourceManager.GetString("RunFlow_AccessToken_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The base URL..
        /// </summary>
        public static string RunFlow_BaseUrl_Description {
            get {
                return ResourceManager.GetString("RunFlow_BaseUrl_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Base URL.
        /// </summary>
        public static string RunFlow_BaseUrl_FriendlyName {
            get {
                return ResourceManager.GetString("RunFlow_BaseUrl_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Runs a cloud flow..
        /// </summary>
        public static string RunFlow_Description {
            get {
                return ResourceManager.GetString("RunFlow_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run flow.
        /// </summary>
        public static string RunFlow_FriendlyName {
            get {
                return ResourceManager.GetString("RunFlow_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The response..
        /// </summary>
        public static string RunFlow_Response_Description {
            get {
                return ResourceManager.GetString("RunFlow_Response_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Response.
        /// </summary>
        public static string RunFlow_Response_FriendlyName {
            get {
                return ResourceManager.GetString("RunFlow_Response_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run a cloud flow..
        /// </summary>
        public static string RunFlow_Summary {
            get {
                return ResourceManager.GetString("RunFlow_Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The identifier of the workflow..
        /// </summary>
        public static string RunFlow_WorkflowId_Description {
            get {
                return ResourceManager.GetString("RunFlow_WorkflowId_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workflow ID.
        /// </summary>
        public static string RunFlow_WorkflowId_FriendlyName {
            get {
                return ResourceManager.GetString("RunFlow_WorkflowId_FriendlyName", resourceCulture);
            }
        }
    }
}
