//-------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------

namespace PowerAutomate.Desktop.Modules.Windows.InputSimulation.Actions.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PowerAutomate.Desktop.Modules.Windows.InputSimulation.Actions.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The check box is selected..
        /// </summary>
        public static string CheckBoxState_Checked_Description {
            get {
                return ResourceManager.GetString("CheckBoxState_Checked_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checked.
        /// </summary>
        public static string CheckBoxState_Checked_FriendlyName {
            get {
                return ResourceManager.GetString("CheckBoxState_Checked_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The check box is neither selected nor cleared..
        /// </summary>
        public static string CheckBoxState_Indeterminate_Description {
            get {
                return ResourceManager.GetString("CheckBoxState_Indeterminate_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indeterminate.
        /// </summary>
        public static string CheckBoxState_Indeterminate_FriendlyName {
            get {
                return ResourceManager.GetString("CheckBoxState_Indeterminate_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The check box is cleared..
        /// </summary>
        public static string CheckBoxState_Unchecked_Description {
            get {
                return ResourceManager.GetString("CheckBoxState_Unchecked_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unchecked.
        /// </summary>
        public static string CheckBoxState_Unchecked_FriendlyName {
            get {
                return ResourceManager.GetString("CheckBoxState_Unchecked_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The button, check box or radio button to press..
        /// </summary>
        public static string ClickButton_Control_Description {
            get {
                return ResourceManager.GetString("ClickButton_Control_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Button.
        /// </summary>
        public static string ClickButton_Control_FriendlyName {
            get {
                return ResourceManager.GetString("ClickButton_Control_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Presses a button, check box or radio button using its own click command instead of screen coordinate [rest of string was truncated]&amp;quot;;.
        /// </summary>
        public static string ClickButton_Description {
            get {
                return ResourceManager.GetString("ClickButton_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click button.
        /// </summary>
        public static string ClickButton_FriendlyName {
            get {
                return ResourceManager.GetString("ClickButton_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press a button without moving the mouse..
        /// </summary>
        public static string ClickButton_Summary {
            get {
                return ResourceManager.GetString("ClickButton_Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The mouse button to press..
        /// </summary>
        public static string ClickControl_Button_Description {
            get {
                return ResourceManager.GetString("ClickControl_Button_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mouse button.
        /// </summary>
        public static string ClickControl_Button_FriendlyName {
            get {
                return ResourceManager.GetString("ClickControl_Button_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The control to send the input to, as found by the Find control action..
        /// </summary>
        public static string ClickControl_Control_Description {
            get {
                return ResourceManager.GetString("ClickControl_Control_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Control.
        /// </summary>
        public static string ClickControl_Control_FriendlyName {
            get {
                return ResourceManager.GetString("ClickControl_Control_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clicks a control by posting mouse messages to it, leaving the mouse pointer where it is. Unlike the  [rest of string was truncated]&amp;quot;;.
        /// </summary>
        public static string ClickControl_Description {
            get {
                return ResourceManager.GetString("ClickControl_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click control.
        /// </summary>
        public static string ClickControl_FriendlyName {
            get {
                return ResourceManager.GetString("ClickControl_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click a control without moving the mouse..
        /// </summary>
        public static string ClickControl_Summary {
            get {
                return ResourceManager.GetString("ClickControl_Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The horizontal position inside the control, in pixels. Leave empty to click the centre..
        /// </summary>
        public static string ClickControl_X_Description {
            get {
                return ResourceManager.GetString("ClickControl_X_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to X position.
        /// </summary>
        public static string ClickControl_X_FriendlyName {
            get {
                return ResourceManager.GetString("ClickControl_X_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The vertical position inside the control, in pixels. Leave empty to click the centre..
        /// </summary>
        public static string ClickControl_Y_Description {
            get {
                return ResourceManager.GetString("ClickControl_Y_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Y position.
        /// </summary>
        public static string ClickControl_Y_FriendlyName {
            get {
                return ResourceManager.GetString("ClickControl_Y_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The mouse button to press..
        /// </summary>
        public static string DoubleClickControl_Button_Description {
            get {
                return ResourceManager.GetString("DoubleClickControl_Button_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mouse button.
        /// </summary>
        public static string DoubleClickControl_Button_FriendlyName {
            get {
                return ResourceManager.GetString("DoubleClickControl_Button_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The control to send the input to, as found by the Find control action..
        /// </summary>
        public static string DoubleClickControl_Control_Description {
            get {
                return ResourceManager.GetString("DoubleClickControl_Control_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Control.
        /// </summary>
        public static string DoubleClickControl_Control_FriendlyName {
            get {
                return ResourceManager.GetString("DoubleClickControl_Control_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Double-clicks a control by posting mouse messages to it, leaving the mouse pointer where it is. Unli [rest of string was truncated]&amp;quot;;.
        /// </summary>
        public static string DoubleClickControl_Description {
            get {
                return ResourceManager.GetString("DoubleClickControl_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Double-click control.
        /// </summary>
        public static string DoubleClickControl_FriendlyName {
            get {
                return ResourceManager.GetString("DoubleClickControl_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Double-click a control without moving the mouse..
        /// </summary>
        public static string DoubleClickControl_Summary {
            get {
                return ResourceManager.GetString("DoubleClickControl_Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The horizontal position inside the control, in pixels. Leave empty to click the centre..
        /// </summary>
        public static string DoubleClickControl_X_Description {
            get {
                return ResourceManager.GetString("DoubleClickControl_X_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to X position.
        /// </summary>
        public static string DoubleClickControl_X_FriendlyName {
            get {
                return ResourceManager.GetString("DoubleClickControl_X_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The vertical position inside the control, in pixels. Leave empty to click the centre..
        /// </summary>
        public static string DoubleClickControl_Y_Description {
            get {
                return ResourceManager.GetString("DoubleClickControl_Y_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Y position.
        /// </summary>
        public static string DoubleClickControl_Y_FriendlyName {
            get {
                return ResourceManager.GetString("DoubleClickControl_Y_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indicates that Windows blocked the input because the target application runs with higher privileges  [rest of string was truncated]&amp;quot;;.
        /// </summary>
        public static string Error_AccessDeniedError_Description {
            get {
                return ResourceManager.GetString("Error_AccessDeniedError_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access denied.
        /// </summary>
        public static string Error_AccessDeniedError_FriendlyName {
            get {
                return ResourceManager.GetString("Error_AccessDeniedError_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indicates that no control matched the supplied search criteria..
        /// </summary>
        public static string Error_ControlNotFoundError_Description {
            get {
                return ResourceManager.GetString("Error_ControlNotFoundError_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Control not found.
        /// </summary>
        public static string Error_ControlNotFoundError_FriendlyName {
            get {
                return ResourceManager.GetString("Error_ControlNotFoundError_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indicates that the target window did not accept the input, or stopped responding before it was proce [rest of string was truncated]&amp;quot;;.
        /// </summary>
        public static string Error_MessageDeliveryError_Description {
            get {
                return ResourceManager.GetString("Error_MessageDeliveryError_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input not delivered.
        /// </summary>
        public static string Error_MessageDeliveryError_FriendlyName {
            get {
                return ResourceManager.GetString("Error_MessageDeliveryError_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indicates that there was a problem when executing the operation..
        /// </summary>
        public static string Error_UnknownError_Description {
            get {
                return ResourceManager.GetString("Error_UnknownError_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation failed.
        /// </summary>
        public static string Error_UnknownError_FriendlyName {
            get {
                return ResourceManager.GetString("Error_UnknownError_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indicates that no window matched the supplied search criteria..
        /// </summary>
        public static string Error_WindowNotFoundError_Description {
            get {
                return ResourceManager.GetString("Error_WindowNotFoundError_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Window not found.
        /// </summary>
        public static string Error_WindowNotFoundError_FriendlyName {
            get {
                return ResourceManager.GetString("Error_WindowNotFoundError_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The control class name to look for, such as Button or Edit. Leave empty to ignore the class..
        /// </summary>
        public static string FindControl_ClassName_Description {
            get {
                return ResourceManager.GetString("FindControl_ClassName_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Control class.
        /// </summary>
        public static string FindControl_ClassName_FriendlyName {
            get {
                return ResourceManager.GetString("FindControl_ClassName_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The control that was found..
        /// </summary>
        public static string FindControl_Control_Description {
            get {
                return ResourceManager.GetString("FindControl_Control_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Control.
        /// </summary>
        public static string FindControl_Control_FriendlyName {
            get {
                return ResourceManager.GetString("FindControl_Control_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The dialog control identifier to look for. Leave empty to ignore the identifier..
        /// </summary>
        public static string FindControl_ControlId_Description {
            get {
                return ResourceManager.GetString("FindControl_ControlId_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Control ID.
        /// </summary>
        public static string FindControl_ControlId_FriendlyName {
            get {
                return ResourceManager.GetString("FindControl_ControlId_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finds a control inside a window by text, class or control identifier..
        /// </summary>
        public static string FindControl_Description {
            get {
                return ResourceManager.GetString("FindControl_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find control.
        /// </summary>
        public static string FindControl_FriendlyName {
            get {
                return ResourceManager.GetString("FindControl_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How the text and class values are compared against each control..
        /// </summary>
        public static string FindControl_MatchMode_Description {
            get {
                return ResourceManager.GetString("FindControl_MatchMode_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Match mode.
        /// </summary>
        public static string FindControl_MatchMode_FriendlyName {
            get {
                return ResourceManager.GetString("FindControl_MatchMode_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specifies whether controls nested inside other controls are searched as well..
        /// </summary>
        public static string FindControl_Recursive_Description {
            get {
                return ResourceManager.GetString("FindControl_Recursive_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search nested controls.
        /// </summary>
        public static string FindControl_Recursive_FriendlyName {
            get {
                return ResourceManager.GetString("FindControl_Recursive_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find a control inside a window..
        /// </summary>
        public static string FindControl_Summary {
            get {
                return ResourceManager.GetString("FindControl_Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The text of the control to look for. Leave empty to ignore the text..
        /// </summary>
        public static string FindControl_Text_Description {
            get {
                return ResourceManager.GetString("FindControl_Text_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Control text.
        /// </summary>
        public static string FindControl_Text_FriendlyName {
            get {
                return ResourceManager.GetString("FindControl_Text_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How long to keep retrying while waiting for the control to appear. Use 0 to search only once..
        /// </summary>
        public static string FindControl_TimeoutMilliseconds_Description {
            get {
                return ResourceManager.GetString("FindControl_TimeoutMilliseconds_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timeout (ms).
        /// </summary>
        public static string FindControl_TimeoutMilliseconds_FriendlyName {
            get {
                return ResourceManager.GetString("FindControl_TimeoutMilliseconds_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The window to search in..
        /// </summary>
        public static string FindControl_Window_Description {
            get {
                return ResourceManager.GetString("FindControl_Window_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Window.
        /// </summary>
        public static string FindControl_Window_FriendlyName {
            get {
                return ResourceManager.GetString("FindControl_Window_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The window class name to look for. Leave empty to ignore the class..
        /// </summary>
        public static string FindWindow_ClassName_Description {
            get {
                return ResourceManager.GetString("FindWindow_ClassName_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Window class.
        /// </summary>
        public static string FindWindow_ClassName_FriendlyName {
            get {
                return ResourceManager.GetString("FindWindow_ClassName_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finds a window on the desktop by title, class or owning process..
        /// </summary>
        public static string FindWindow_Description {
            get {
                return ResourceManager.GetString("FindWindow_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find window.
        /// </summary>
        public static string FindWindow_FriendlyName {
            get {
                return ResourceManager.GetString("FindWindow_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How the title and class values are compared against each window..
        /// </summary>
        public static string FindWindow_MatchMode_Description {
            get {
                return ResourceManager.GetString("FindWindow_MatchMode_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Match mode.
        /// </summary>
        public static string FindWindow_MatchMode_FriendlyName {
            get {
                return ResourceManager.GetString("FindWindow_MatchMode_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restricts the search to windows owned by this process. Leave empty to search every process..
        /// </summary>
        public static string FindWindow_ProcessId_Description {
            get {
                return ResourceManager.GetString("FindWindow_ProcessId_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process ID.
        /// </summary>
        public static string FindWindow_ProcessId_FriendlyName {
            get {
                return ResourceManager.GetString("FindWindow_ProcessId_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find a window on the desktop..
        /// </summary>
        public static string FindWindow_Summary {
            get {
                return ResourceManager.GetString("FindWindow_Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How long to keep retrying while waiting for the window to appear. Use 0 to search only once..
        /// </summary>
        public static string FindWindow_TimeoutMilliseconds_Description {
            get {
                return ResourceManager.GetString("FindWindow_TimeoutMilliseconds_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timeout (ms).
        /// </summary>
        public static string FindWindow_TimeoutMilliseconds_FriendlyName {
            get {
                return ResourceManager.GetString("FindWindow_TimeoutMilliseconds_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The title of the window to look for. Leave empty to ignore the title..
        /// </summary>
        public static string FindWindow_Title_Description {
            get {
                return ResourceManager.GetString("FindWindow_Title_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Window title.
        /// </summary>
        public static string FindWindow_Title_FriendlyName {
            get {
                return ResourceManager.GetString("FindWindow_Title_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The window that was found..
        /// </summary>
        public static string FindWindow_Window_Description {
            get {
                return ResourceManager.GetString("FindWindow_Window_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Window.
        /// </summary>
        public static string FindWindow_Window_FriendlyName {
            get {
                return ResourceManager.GetString("FindWindow_Window_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The controls that were found..
        /// </summary>
        public static string GetControls_Controls_Description {
            get {
                return ResourceManager.GetString("GetControls_Controls_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controls.
        /// </summary>
        public static string GetControls_Controls_FriendlyName {
            get {
                return ResourceManager.GetString("GetControls_Controls_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retrieves every control contained in a window..
        /// </summary>
        public static string GetControls_Description {
            get {
                return ResourceManager.GetString("GetControls_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get controls.
        /// </summary>
        public static string GetControls_FriendlyName {
            get {
                return ResourceManager.GetString("GetControls_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specifies whether controls nested inside other controls are included..
        /// </summary>
        public static string GetControls_Recursive_Description {
            get {
                return ResourceManager.GetString("GetControls_Recursive_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include nested controls.
        /// </summary>
        public static string GetControls_Recursive_FriendlyName {
            get {
                return ResourceManager.GetString("GetControls_Recursive_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get the controls of a window..
        /// </summary>
        public static string GetControls_Summary {
            get {
                return ResourceManager.GetString("GetControls_Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The window to list the controls of..
        /// </summary>
        public static string GetControls_Window_Description {
            get {
                return ResourceManager.GetString("GetControls_Window_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Window.
        /// </summary>
        public static string GetControls_Window_FriendlyName {
            get {
                return ResourceManager.GetString("GetControls_Window_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The control to send the input to, as found by the Find control action..
        /// </summary>
        public static string GetControlText_Control_Description {
            get {
                return ResourceManager.GetString("GetControlText_Control_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Control.
        /// </summary>
        public static string GetControlText_Control_FriendlyName {
            get {
                return ResourceManager.GetString("GetControlText_Control_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reads the text of a control, including controls owned by another application..
        /// </summary>
        public static string GetControlText_Description {
            get {
                return ResourceManager.GetString("GetControlText_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get control text.
        /// </summary>
        public static string GetControlText_FriendlyName {
            get {
                return ResourceManager.GetString("GetControlText_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get the text of a control..
        /// </summary>
        public static string GetControlText_Summary {
            get {
                return ResourceManager.GetString("GetControlText_Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The text of the control..
        /// </summary>
        public static string GetControlText_Text_Description {
            get {
                return ResourceManager.GetString("GetControlText_Text_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text.
        /// </summary>
        public static string GetControlText_Text_FriendlyName {
            get {
                return ResourceManager.GetString("GetControlText_Text_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The left mouse button..
        /// </summary>
        public static string MouseButton_Left_Description {
            get {
                return ResourceManager.GetString("MouseButton_Left_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left.
        /// </summary>
        public static string MouseButton_Left_FriendlyName {
            get {
                return ResourceManager.GetString("MouseButton_Left_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The middle mouse button..
        /// </summary>
        public static string MouseButton_Middle_Description {
            get {
                return ResourceManager.GetString("MouseButton_Middle_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Middle.
        /// </summary>
        public static string MouseButton_Middle_FriendlyName {
            get {
                return ResourceManager.GetString("MouseButton_Middle_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The right mouse button..
        /// </summary>
        public static string MouseButton_Right_Description {
            get {
                return ResourceManager.GetString("MouseButton_Right_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right.
        /// </summary>
        public static string MouseButton_Right_FriendlyName {
            get {
                return ResourceManager.GetString("MouseButton_Right_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The control to send the input to, as found by the Find control action..
        /// </summary>
        public static string ScrollControl_Control_Description {
            get {
                return ResourceManager.GetString("ScrollControl_Control_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Control.
        /// </summary>
        public static string ScrollControl_Control_FriendlyName {
            get {
                return ResourceManager.GetString("ScrollControl_Control_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scrolls a control by sending mouse wheel messages to it, leaving the mouse pointer where it is..
        /// </summary>
        public static string ScrollControl_Description {
            get {
                return ResourceManager.GetString("ScrollControl_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The direction to scroll in..
        /// </summary>
        public static string ScrollControl_Direction_Description {
            get {
                return ResourceManager.GetString("ScrollControl_Direction_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Direction.
        /// </summary>
        public static string ScrollControl_Direction_FriendlyName {
            get {
                return ResourceManager.GetString("ScrollControl_Direction_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scroll control.
        /// </summary>
        public static string ScrollControl_FriendlyName {
            get {
                return ResourceManager.GetString("ScrollControl_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How many wheel notches to scroll..
        /// </summary>
        public static string ScrollControl_Notches_Description {
            get {
                return ResourceManager.GetString("ScrollControl_Notches_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wheel notches.
        /// </summary>
        public static string ScrollControl_Notches_FriendlyName {
            get {
                return ResourceManager.GetString("ScrollControl_Notches_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scroll a control without moving the mouse..
        /// </summary>
        public static string ScrollControl_Summary {
            get {
                return ResourceManager.GetString("ScrollControl_Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scroll towards the end of the content..
        /// </summary>
        public static string ScrollDirection_Down_Description {
            get {
                return ResourceManager.GetString("ScrollDirection_Down_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Down.
        /// </summary>
        public static string ScrollDirection_Down_FriendlyName {
            get {
                return ResourceManager.GetString("ScrollDirection_Down_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scroll towards the beginning of the content..
        /// </summary>
        public static string ScrollDirection_Up_Description {
            get {
                return ResourceManager.GetString("ScrollDirection_Up_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Up.
        /// </summary>
        public static string ScrollDirection_Up_FriendlyName {
            get {
                return ResourceManager.GetString("ScrollDirection_Up_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The combo box to update..
        /// </summary>
        public static string SelectComboBoxItem_Control_Description {
            get {
                return ResourceManager.GetString("SelectComboBoxItem_Control_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Combo box.
        /// </summary>
        public static string SelectComboBoxItem_Control_FriendlyName {
            get {
                return ResourceManager.GetString("SelectComboBoxItem_Control_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selects an item in a combo box by text or position and notifies the application of the change..
        /// </summary>
        public static string SelectComboBoxItem_Description {
            get {
                return ResourceManager.GetString("SelectComboBoxItem_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select combo box item.
        /// </summary>
        public static string SelectComboBoxItem_FriendlyName {
            get {
                return ResourceManager.GetString("SelectComboBoxItem_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The zero-based position of the item to select. Leave empty to select by text..
        /// </summary>
        public static string SelectComboBoxItem_Index_Description {
            get {
                return ResourceManager.GetString("SelectComboBoxItem_Index_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item position.
        /// </summary>
        public static string SelectComboBoxItem_Index_FriendlyName {
            get {
                return ResourceManager.GetString("SelectComboBoxItem_Index_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The zero-based position of the item that was selected..
        /// </summary>
        public static string SelectComboBoxItem_SelectedIndex_Description {
            get {
                return ResourceManager.GetString("SelectComboBoxItem_SelectedIndex_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected position.
        /// </summary>
        public static string SelectComboBoxItem_SelectedIndex_FriendlyName {
            get {
                return ResourceManager.GetString("SelectComboBoxItem_SelectedIndex_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select an item in a combo box..
        /// </summary>
        public static string SelectComboBoxItem_Summary {
            get {
                return ResourceManager.GetString("SelectComboBoxItem_Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The exact text of the item to select. Ignored when a position is supplied..
        /// </summary>
        public static string SelectComboBoxItem_Text_Description {
            get {
                return ResourceManager.GetString("SelectComboBoxItem_Text_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item text.
        /// </summary>
        public static string SelectComboBoxItem_Text_FriendlyName {
            get {
                return ResourceManager.GetString("SelectComboBoxItem_Text_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The list box to update..
        /// </summary>
        public static string SelectListBoxItem_Control_Description {
            get {
                return ResourceManager.GetString("SelectListBoxItem_Control_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List box.
        /// </summary>
        public static string SelectListBoxItem_Control_FriendlyName {
            get {
                return ResourceManager.GetString("SelectListBoxItem_Control_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selects an item in a list box by text or position and notifies the application of the change..
        /// </summary>
        public static string SelectListBoxItem_Description {
            get {
                return ResourceManager.GetString("SelectListBoxItem_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select list box item.
        /// </summary>
        public static string SelectListBoxItem_FriendlyName {
            get {
                return ResourceManager.GetString("SelectListBoxItem_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The zero-based position of the item to select. Leave empty to select by text..
        /// </summary>
        public static string SelectListBoxItem_Index_Description {
            get {
                return ResourceManager.GetString("SelectListBoxItem_Index_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item position.
        /// </summary>
        public static string SelectListBoxItem_Index_FriendlyName {
            get {
                return ResourceManager.GetString("SelectListBoxItem_Index_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The zero-based position of the item that was selected..
        /// </summary>
        public static string SelectListBoxItem_SelectedIndex_Description {
            get {
                return ResourceManager.GetString("SelectListBoxItem_SelectedIndex_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected position.
        /// </summary>
        public static string SelectListBoxItem_SelectedIndex_FriendlyName {
            get {
                return ResourceManager.GetString("SelectListBoxItem_SelectedIndex_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select an item in a list box..
        /// </summary>
        public static string SelectListBoxItem_Summary {
            get {
                return ResourceManager.GetString("SelectListBoxItem_Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The exact text of the item to select. Ignored when a position is supplied..
        /// </summary>
        public static string SelectListBoxItem_Text_Description {
            get {
                return ResourceManager.GetString("SelectListBoxItem_Text_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item text.
        /// </summary>
        public static string SelectListBoxItem_Text_FriendlyName {
            get {
                return ResourceManager.GetString("SelectListBoxItem_Text_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The control to send the input to, as found by the Find control action..
        /// </summary>
        public static string SendKey_Control_Description {
            get {
                return ResourceManager.GetString("SendKey_Control_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Control.
        /// </summary>
        public static string SendKey_Control_FriendlyName {
            get {
                return ResourceManager.GetString("SendKey_Control_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sends a single key, such as Enter or Tab, to a control without using the physical keyboard..
        /// </summary>
        public static string SendKey_Description {
            get {
                return ResourceManager.GetString("SendKey_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send key.
        /// </summary>
        public static string SendKey_FriendlyName {
            get {
                return ResourceManager.GetString("SendKey_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The key to send to the control..
        /// </summary>
        public static string SendKey_Key_Description {
            get {
                return ResourceManager.GetString("SendKey_Key_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key.
        /// </summary>
        public static string SendKey_Key_FriendlyName {
            get {
                return ResourceManager.GetString("SendKey_Key_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send a key to a control without using the keyboard..
        /// </summary>
        public static string SendKey_Summary {
            get {
                return ResourceManager.GetString("SendKey_Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The control to send the input to, as found by the Find control action..
        /// </summary>
        public static string SendText_Control_Description {
            get {
                return ResourceManager.GetString("SendText_Control_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Control.
        /// </summary>
        public static string SendText_Control_FriendlyName {
            get {
                return ResourceManager.GetString("SendText_Control_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How long to pause between characters, for applications that cannot keep up with fast typing..
        /// </summary>
        public static string SendText_DelayMilliseconds_Description {
            get {
                return ResourceManager.GetString("SendText_DelayMilliseconds_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delay between characters (ms).
        /// </summary>
        public static string SendText_DelayMilliseconds_FriendlyName {
            get {
                return ResourceManager.GetString("SendText_DelayMilliseconds_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Types text into a control one character at a time by posting keyboard messages, for Win32 controls t [rest of string was truncated]&amp;quot;;.
        /// </summary>
        public static string SendText_Description {
            get {
                return ResourceManager.GetString("SendText_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send text.
        /// </summary>
        public static string SendText_FriendlyName {
            get {
                return ResourceManager.GetString("SendText_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type text into a control without using the keyboard..
        /// </summary>
        public static string SendText_Summary {
            get {
                return ResourceManager.GetString("SendText_Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The text to type into the control..
        /// </summary>
        public static string SendText_Text_Description {
            get {
                return ResourceManager.GetString("SendText_Text_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text.
        /// </summary>
        public static string SendText_Text_FriendlyName {
            get {
                return ResourceManager.GetString("SendText_Text_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The check box or radio button to update..
        /// </summary>
        public static string SetCheckBoxState_Control_Description {
            get {
                return ResourceManager.GetString("SetCheckBoxState_Control_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check box.
        /// </summary>
        public static string SetCheckBoxState_Control_FriendlyName {
            get {
                return ResourceManager.GetString("SetCheckBoxState_Control_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checks, unchecks or sets a check box to the indeterminate state..
        /// </summary>
        public static string SetCheckBoxState_Description {
            get {
                return ResourceManager.GetString("SetCheckBoxState_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set check box state.
        /// </summary>
        public static string SetCheckBoxState_FriendlyName {
            get {
                return ResourceManager.GetString("SetCheckBoxState_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The state to apply to the check box..
        /// </summary>
        public static string SetCheckBoxState_State_Description {
            get {
                return ResourceManager.GetString("SetCheckBoxState_State_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State.
        /// </summary>
        public static string SetCheckBoxState_State_FriendlyName {
            get {
                return ResourceManager.GetString("SetCheckBoxState_State_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set the state of a check box..
        /// </summary>
        public static string SetCheckBoxState_Summary {
            get {
                return ResourceManager.GetString("SetCheckBoxState_Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The control to send the input to, as found by the Find control action..
        /// </summary>
        public static string SetControlText_Control_Description {
            get {
                return ResourceManager.GetString("SetControlText_Control_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Control.
        /// </summary>
        public static string SetControlText_Control_FriendlyName {
            get {
                return ResourceManager.GetString("SetControlText_Control_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replaces the whole text of a control in one step..
        /// </summary>
        public static string SetControlText_Description {
            get {
                return ResourceManager.GetString("SetControlText_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set control text.
        /// </summary>
        public static string SetControlText_FriendlyName {
            get {
                return ResourceManager.GetString("SetControlText_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set the text of a control..
        /// </summary>
        public static string SetControlText_Summary {
            get {
                return ResourceManager.GetString("SetControlText_Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The text to place in the control..
        /// </summary>
        public static string SetControlText_Text_Description {
            get {
                return ResourceManager.GetString("SetControlText_Text_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text.
        /// </summary>
        public static string SetControlText_Text_FriendlyName {
            get {
                return ResourceManager.GetString("SetControlText_Text_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value must appear anywhere in the text..
        /// </summary>
        public static string TextMatchMode_Contains_Description {
            get {
                return ResourceManager.GetString("TextMatchMode_Contains_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contains.
        /// </summary>
        public static string TextMatchMode_Contains_FriendlyName {
            get {
                return ResourceManager.GetString("TextMatchMode_Contains_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value must match the whole text..
        /// </summary>
        public static string TextMatchMode_Equals_Description {
            get {
                return ResourceManager.GetString("TextMatchMode_Equals_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equals.
        /// </summary>
        public static string TextMatchMode_Equals_FriendlyName {
            get {
                return ResourceManager.GetString("TextMatchMode_Equals_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The text must begin with the value..
        /// </summary>
        public static string TextMatchMode_StartsWith_Description {
            get {
                return ResourceManager.GetString("TextMatchMode_StartsWith_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starts with.
        /// </summary>
        public static string TextMatchMode_StartsWith_FriendlyName {
            get {
                return ResourceManager.GetString("TextMatchMode_StartsWith_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Down arrow key..
        /// </summary>
        public static string VirtualKey_ArrowDown_Description {
            get {
                return ResourceManager.GetString("VirtualKey_ArrowDown_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Down arrow.
        /// </summary>
        public static string VirtualKey_ArrowDown_FriendlyName {
            get {
                return ResourceManager.GetString("VirtualKey_ArrowDown_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Left arrow key..
        /// </summary>
        public static string VirtualKey_ArrowLeft_Description {
            get {
                return ResourceManager.GetString("VirtualKey_ArrowLeft_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left arrow.
        /// </summary>
        public static string VirtualKey_ArrowLeft_FriendlyName {
            get {
                return ResourceManager.GetString("VirtualKey_ArrowLeft_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Right arrow key..
        /// </summary>
        public static string VirtualKey_ArrowRight_Description {
            get {
                return ResourceManager.GetString("VirtualKey_ArrowRight_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right arrow.
        /// </summary>
        public static string VirtualKey_ArrowRight_FriendlyName {
            get {
                return ResourceManager.GetString("VirtualKey_ArrowRight_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Up arrow key..
        /// </summary>
        public static string VirtualKey_ArrowUp_Description {
            get {
                return ResourceManager.GetString("VirtualKey_ArrowUp_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Up arrow.
        /// </summary>
        public static string VirtualKey_ArrowUp_FriendlyName {
            get {
                return ResourceManager.GetString("VirtualKey_ArrowUp_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Backspace key..
        /// </summary>
        public static string VirtualKey_Backspace_Description {
            get {
                return ResourceManager.GetString("VirtualKey_Backspace_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backspace.
        /// </summary>
        public static string VirtualKey_Backspace_FriendlyName {
            get {
                return ResourceManager.GetString("VirtualKey_Backspace_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Delete key..
        /// </summary>
        public static string VirtualKey_Delete_Description {
            get {
                return ResourceManager.GetString("VirtualKey_Delete_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string VirtualKey_Delete_FriendlyName {
            get {
                return ResourceManager.GetString("VirtualKey_Delete_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The End key..
        /// </summary>
        public static string VirtualKey_End_Description {
            get {
                return ResourceManager.GetString("VirtualKey_End_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End.
        /// </summary>
        public static string VirtualKey_End_FriendlyName {
            get {
                return ResourceManager.GetString("VirtualKey_End_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Enter key..
        /// </summary>
        public static string VirtualKey_Enter_Description {
            get {
                return ResourceManager.GetString("VirtualKey_Enter_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter.
        /// </summary>
        public static string VirtualKey_Enter_FriendlyName {
            get {
                return ResourceManager.GetString("VirtualKey_Enter_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Escape key..
        /// </summary>
        public static string VirtualKey_Escape_Description {
            get {
                return ResourceManager.GetString("VirtualKey_Escape_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Escape.
        /// </summary>
        public static string VirtualKey_Escape_FriendlyName {
            get {
                return ResourceManager.GetString("VirtualKey_Escape_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The F1 key..
        /// </summary>
        public static string VirtualKey_F1_Description {
            get {
                return ResourceManager.GetString("VirtualKey_F1_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to F1.
        /// </summary>
        public static string VirtualKey_F1_FriendlyName {
            get {
                return ResourceManager.GetString("VirtualKey_F1_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The F10 key..
        /// </summary>
        public static string VirtualKey_F10_Description {
            get {
                return ResourceManager.GetString("VirtualKey_F10_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to F10.
        /// </summary>
        public static string VirtualKey_F10_FriendlyName {
            get {
                return ResourceManager.GetString("VirtualKey_F10_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The F11 key..
        /// </summary>
        public static string VirtualKey_F11_Description {
            get {
                return ResourceManager.GetString("VirtualKey_F11_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to F11.
        /// </summary>
        public static string VirtualKey_F11_FriendlyName {
            get {
                return ResourceManager.GetString("VirtualKey_F11_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The F12 key..
        /// </summary>
        public static string VirtualKey_F12_Description {
            get {
                return ResourceManager.GetString("VirtualKey_F12_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to F12.
        /// </summary>
        public static string VirtualKey_F12_FriendlyName {
            get {
                return ResourceManager.GetString("VirtualKey_F12_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The F2 key..
        /// </summary>
        public static string VirtualKey_F2_Description {
            get {
                return ResourceManager.GetString("VirtualKey_F2_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to F2.
        /// </summary>
        public static string VirtualKey_F2_FriendlyName {
            get {
                return ResourceManager.GetString("VirtualKey_F2_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The F3 key..
        /// </summary>
        public static string VirtualKey_F3_Description {
            get {
                return ResourceManager.GetString("VirtualKey_F3_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to F3.
        /// </summary>
        public static string VirtualKey_F3_FriendlyName {
            get {
                return ResourceManager.GetString("VirtualKey_F3_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The F4 key..
        /// </summary>
        public static string VirtualKey_F4_Description {
            get {
                return ResourceManager.GetString("VirtualKey_F4_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to F4.
        /// </summary>
        public static string VirtualKey_F4_FriendlyName {
            get {
                return ResourceManager.GetString("VirtualKey_F4_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The F5 key..
        /// </summary>
        public static string VirtualKey_F5_Description {
            get {
                return ResourceManager.GetString("VirtualKey_F5_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to F5.
        /// </summary>
        public static string VirtualKey_F5_FriendlyName {
            get {
                return ResourceManager.GetString("VirtualKey_F5_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The F6 key..
        /// </summary>
        public static string VirtualKey_F6_Description {
            get {
                return ResourceManager.GetString("VirtualKey_F6_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to F6.
        /// </summary>
        public static string VirtualKey_F6_FriendlyName {
            get {
                return ResourceManager.GetString("VirtualKey_F6_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The F7 key..
        /// </summary>
        public static string VirtualKey_F7_Description {
            get {
                return ResourceManager.GetString("VirtualKey_F7_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to F7.
        /// </summary>
        public static string VirtualKey_F7_FriendlyName {
            get {
                return ResourceManager.GetString("VirtualKey_F7_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The F8 key..
        /// </summary>
        public static string VirtualKey_F8_Description {
            get {
                return ResourceManager.GetString("VirtualKey_F8_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to F8.
        /// </summary>
        public static string VirtualKey_F8_FriendlyName {
            get {
                return ResourceManager.GetString("VirtualKey_F8_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The F9 key..
        /// </summary>
        public static string VirtualKey_F9_Description {
            get {
                return ResourceManager.GetString("VirtualKey_F9_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to F9.
        /// </summary>
        public static string VirtualKey_F9_FriendlyName {
            get {
                return ResourceManager.GetString("VirtualKey_F9_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Home key..
        /// </summary>
        public static string VirtualKey_Home_Description {
            get {
                return ResourceManager.GetString("VirtualKey_Home_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string VirtualKey_Home_FriendlyName {
            get {
                return ResourceManager.GetString("VirtualKey_Home_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Insert key..
        /// </summary>
        public static string VirtualKey_Insert_Description {
            get {
                return ResourceManager.GetString("VirtualKey_Insert_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert.
        /// </summary>
        public static string VirtualKey_Insert_FriendlyName {
            get {
                return ResourceManager.GetString("VirtualKey_Insert_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Page down key..
        /// </summary>
        public static string VirtualKey_PageDown_Description {
            get {
                return ResourceManager.GetString("VirtualKey_PageDown_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page down.
        /// </summary>
        public static string VirtualKey_PageDown_FriendlyName {
            get {
                return ResourceManager.GetString("VirtualKey_PageDown_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Page up key..
        /// </summary>
        public static string VirtualKey_PageUp_Description {
            get {
                return ResourceManager.GetString("VirtualKey_PageUp_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page up.
        /// </summary>
        public static string VirtualKey_PageUp_FriendlyName {
            get {
                return ResourceManager.GetString("VirtualKey_PageUp_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Space key..
        /// </summary>
        public static string VirtualKey_Space_Description {
            get {
                return ResourceManager.GetString("VirtualKey_Space_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Space.
        /// </summary>
        public static string VirtualKey_Space_FriendlyName {
            get {
                return ResourceManager.GetString("VirtualKey_Space_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Tab key..
        /// </summary>
        public static string VirtualKey_Tab_Description {
            get {
                return ResourceManager.GetString("VirtualKey_Tab_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tab.
        /// </summary>
        public static string VirtualKey_Tab_FriendlyName {
            get {
                return ResourceManager.GetString("VirtualKey_Tab_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drives legacy Win32 windows and controls by posting window messages, without moving the mouse pointe [rest of string was truncated]&amp;quot;;.
        /// </summary>
        public static string WindowsInputSimulation_Description {
            get {
                return ResourceManager.GetString("WindowsInputSimulation_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows input simulation.
        /// </summary>
        public static string WindowsInputSimulation_FriendlyName {
            get {
                return ResourceManager.GetString("WindowsInputSimulation_FriendlyName", resourceCulture);
            }
        }
    }
}
