//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PowerAutomate.Desktop.Modules.Redis.Actions.Properties {
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PowerAutomate.Desktop.Modules.Redis.Actions.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The Redis connection to close..
        /// </summary>
        public static string CloseConnection_Connection_Description {
            get {
                return ResourceManager.GetString("CloseConnection_Connection_Description", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Connection.
        /// </summary>
        public static string CloseConnection_Connection_FriendlyName {
            get {
                return ResourceManager.GetString("CloseConnection_Connection_FriendlyName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Release an open Redis connection..
        /// </summary>
        public static string CloseConnection_Description {
            get {
                return ResourceManager.GetString("CloseConnection_Description", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Close Redis connection.
        /// </summary>
        public static string CloseConnection_FriendlyName {
            get {
                return ResourceManager.GetString("CloseConnection_FriendlyName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Close a Redis connection..
        /// </summary>
        public static string CloseConnection_Summary {
            get {
                return ResourceManager.GetString("CloseConnection_Summary", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to StackExchange.Redis configuration string, including the endpoint..
        /// </summary>
        public static string Connect_Configuration_Description {
            get {
                return ResourceManager.GetString("Connect_Configuration_Description", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Configuration.
        /// </summary>
        public static string Connect_Configuration_FriendlyName {
            get {
                return ResourceManager.GetString("Connect_Configuration_FriendlyName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Reusable connection for subsequent Redis actions..
        /// </summary>
        public static string Connect_Connection_Description {
            get {
                return ResourceManager.GetString("Connect_Connection_Description", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Connection.
        /// </summary>
        public static string Connect_Connection_FriendlyName {
            get {
                return ResourceManager.GetString("Connect_Connection_FriendlyName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Redis database index; -1 uses the configured default..
        /// </summary>
        public static string Connect_DatabaseNumber_Description {
            get {
                return ResourceManager.GetString("Connect_DatabaseNumber_Description", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Database number.
        /// </summary>
        public static string Connect_DatabaseNumber_FriendlyName {
            get {
                return ResourceManager.GetString("Connect_DatabaseNumber_FriendlyName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Open a reusable connection to a Redis server..
        /// </summary>
        public static string Connect_Description {
            get {
                return ResourceManager.GetString("Connect_Description", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Connect to Redis.
        /// </summary>
        public static string Connect_FriendlyName {
            get {
                return ResourceManager.GetString("Connect_FriendlyName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Connect to Redis..
        /// </summary>
        public static string Connect_Summary {
            get {
                return ResourceManager.GetString("Connect_Summary", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to An open Redis connection..
        /// </summary>
        public static string DeleteKey_Connection_Description {
            get {
                return ResourceManager.GetString("DeleteKey_Connection_Description", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Connection.
        /// </summary>
        public static string DeleteKey_Connection_FriendlyName {
            get {
                return ResourceManager.GetString("DeleteKey_Connection_FriendlyName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Delete a key from Redis..
        /// </summary>
        public static string DeleteKey_Description {
            get {
                return ResourceManager.GetString("DeleteKey_Description", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Delete Redis key.
        /// </summary>
        public static string DeleteKey_FriendlyName {
            get {
                return ResourceManager.GetString("DeleteKey_FriendlyName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Whether an existing key was deleted..
        /// </summary>
        public static string DeleteKey_IsDeleted_Description {
            get {
                return ResourceManager.GetString("DeleteKey_IsDeleted_Description", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Deleted.
        /// </summary>
        public static string DeleteKey_IsDeleted_FriendlyName {
            get {
                return ResourceManager.GetString("DeleteKey_IsDeleted_FriendlyName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Redis key to delete..
        /// </summary>
        public static string DeleteKey_Key_Description {
            get {
                return ResourceManager.GetString("DeleteKey_Key_Description", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Key.
        /// </summary>
        public static string DeleteKey_Key_FriendlyName {
            get {
                return ResourceManager.GetString("DeleteKey_Key_FriendlyName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Remove a Redis key..
        /// </summary>
        public static string DeleteKey_Summary {
            get {
                return ResourceManager.GetString("DeleteKey_Summary", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The Redis connection has already been closed..
        /// </summary>
        public static string Error_ClosedConnectionError_Description {
            get {
                return ResourceManager.GetString("Error_ClosedConnectionError_Description", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Connection closed.
        /// </summary>
        public static string Error_ClosedConnectionError_FriendlyName {
            get {
                return ResourceManager.GetString("Error_ClosedConnectionError_FriendlyName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to A required connection or input is invalid..
        /// </summary>
        public static string Error_InvalidArgumentError_Description {
            get {
                return ResourceManager.GetString("Error_InvalidArgumentError_Description", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Invalid input.
        /// </summary>
        public static string Error_InvalidArgumentError_FriendlyName {
            get {
                return ResourceManager.GetString("Error_InvalidArgumentError_FriendlyName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Redis rejected the operation or the connection failed..
        /// </summary>
        public static string Error_RedisError_Description {
            get {
                return ResourceManager.GetString("Error_RedisError_Description", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Redis error.
        /// </summary>
        public static string Error_RedisError_FriendlyName {
            get {
                return ResourceManager.GetString("Error_RedisError_FriendlyName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to An open Redis connection..
        /// </summary>
        public static string GetValue_Connection_Description {
            get {
                return ResourceManager.GetString("GetValue_Connection_Description", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Connection.
        /// </summary>
        public static string GetValue_Connection_FriendlyName {
            get {
                return ResourceManager.GetString("GetValue_Connection_FriendlyName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Read a string value from a Redis key..
        /// </summary>
        public static string GetValue_Description {
            get {
                return ResourceManager.GetString("GetValue_Description", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Get Redis value.
        /// </summary>
        public static string GetValue_FriendlyName {
            get {
                return ResourceManager.GetString("GetValue_FriendlyName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Whether the key exists..
        /// </summary>
        public static string GetValue_IsFound_Description {
            get {
                return ResourceManager.GetString("GetValue_IsFound_Description", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Found.
        /// </summary>
        public static string GetValue_IsFound_FriendlyName {
            get {
                return ResourceManager.GetString("GetValue_IsFound_FriendlyName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Redis key to read..
        /// </summary>
        public static string GetValue_Key_Description {
            get {
                return ResourceManager.GetString("GetValue_Key_Description", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Key.
        /// </summary>
        public static string GetValue_Key_FriendlyName {
            get {
                return ResourceManager.GetString("GetValue_Key_FriendlyName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Read a Redis string key..
        /// </summary>
        public static string GetValue_Summary {
            get {
                return ResourceManager.GetString("GetValue_Summary", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Stored string value; null when the key is missing..
        /// </summary>
        public static string GetValue_Value_Description {
            get {
                return ResourceManager.GetString("GetValue_Value_Description", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        public static string GetValue_Value_FriendlyName {
            get {
                return ResourceManager.GetString("GetValue_Value_FriendlyName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Work with Redis string keys..
        /// </summary>
        public static string Redis_Description {
            get {
                return ResourceManager.GetString("Redis_Description", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Redis.
        /// </summary>
        public static string Redis_FriendlyName {
            get {
                return ResourceManager.GetString("Redis_FriendlyName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Redis connection.
        /// </summary>
        public static string RedisConnection_FriendlyName {
            get {
                return ResourceManager.GetString("RedisConnection_FriendlyName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Redis connections.
        /// </summary>
        public static string RedisConnection_FriendlyNamePlural {
            get {
                return ResourceManager.GetString("RedisConnection_FriendlyNamePlural", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to An open Redis connection..
        /// </summary>
        public static string SetValue_Connection_Description {
            get {
                return ResourceManager.GetString("SetValue_Connection_Description", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Connection.
        /// </summary>
        public static string SetValue_Connection_FriendlyName {
            get {
                return ResourceManager.GetString("SetValue_Connection_FriendlyName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Store a string value under a Redis key..
        /// </summary>
        public static string SetValue_Description {
            get {
                return ResourceManager.GetString("SetValue_Description", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Seconds until expiry; zero means no expiry..
        /// </summary>
        public static string SetValue_ExpirySeconds_Description {
            get {
                return ResourceManager.GetString("SetValue_ExpirySeconds_Description", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Expiry in seconds.
        /// </summary>
        public static string SetValue_ExpirySeconds_FriendlyName {
            get {
                return ResourceManager.GetString("SetValue_ExpirySeconds_FriendlyName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Set Redis value.
        /// </summary>
        public static string SetValue_FriendlyName {
            get {
                return ResourceManager.GetString("SetValue_FriendlyName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Whether the server stored the value..
        /// </summary>
        public static string SetValue_IsStored_Description {
            get {
                return ResourceManager.GetString("SetValue_IsStored_Description", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Was set.
        /// </summary>
        public static string SetValue_IsStored_FriendlyName {
            get {
                return ResourceManager.GetString("SetValue_IsStored_FriendlyName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Redis key to write..
        /// </summary>
        public static string SetValue_Key_Description {
            get {
                return ResourceManager.GetString("SetValue_Key_Description", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Key.
        /// </summary>
        public static string SetValue_Key_FriendlyName {
            get {
                return ResourceManager.GetString("SetValue_Key_FriendlyName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Write a Redis string key..
        /// </summary>
        public static string SetValue_Summary {
            get {
                return ResourceManager.GetString("SetValue_Summary", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to String value to store, including the empty string..
        /// </summary>
        public static string SetValue_Value_Description {
            get {
                return ResourceManager.GetString("SetValue_Value_Description", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        public static string SetValue_Value_FriendlyName {
            get {
                return ResourceManager.GetString("SetValue_Value_FriendlyName", resourceCulture);
            }
        }
    }
}
