//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PowerAutomate.Desktop.Modules.WindowsRegistry.Actions.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PowerAutomate.Desktop.Modules.WindowsRegistry.Actions.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indicates that there was a problem setting the registry value.
        /// </summary>
        internal static string Error_UnknownError_Description {
            get {
                return ResourceManager.GetString("Error_UnknownError_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to set the registry value.
        /// </summary>
        internal static string Error_UnknownError_FriendlyName {
            get {
                return ResourceManager.GetString("Error_UnknownError_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Binary.
        /// </summary>
        internal static string RegistryValueKind_Binary_FriendlyName {
            get {
                return ResourceManager.GetString("RegistryValueKind_Binary_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DWORD (32-bit).
        /// </summary>
        internal static string RegistryValueKind_DWord_FriendlyName {
            get {
                return ResourceManager.GetString("RegistryValueKind_DWord_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expandable String.
        /// </summary>
        internal static string RegistryValueKind_ExpandString_FriendlyName {
            get {
                return ResourceManager.GetString("RegistryValueKind_ExpandString_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multi-String.
        /// </summary>
        internal static string RegistryValueKind_MultiString_FriendlyName {
            get {
                return ResourceManager.GetString("RegistryValueKind_MultiString_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QWORD (64-bit).
        /// </summary>
        internal static string RegistryValueKind_QWord_FriendlyName {
            get {
                return ResourceManager.GetString("RegistryValueKind_QWord_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to String.
        /// </summary>
        internal static string RegistryValueKind_String_FriendlyName {
            get {
                return ResourceManager.GetString("RegistryValueKind_String_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The binary data..
        /// </summary>
        internal static string SetRegistryValueAction_Binary_Description {
            get {
                return ResourceManager.GetString("SetRegistryValueAction_Binary_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        internal static string SetRegistryValueAction_Binary_FriendlyName {
            get {
                return ResourceManager.GetString("SetRegistryValueAction_Binary_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sets the value of a name/value pair in the registry key..
        /// </summary>
        internal static string SetRegistryValueAction_Description {
            get {
                return ResourceManager.GetString("SetRegistryValueAction_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The 32-bit number..
        /// </summary>
        internal static string SetRegistryValueAction_DWord_Description {
            get {
                return ResourceManager.GetString("SetRegistryValueAction_DWord_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        internal static string SetRegistryValueAction_DWord_FriendlyName {
            get {
                return ResourceManager.GetString("SetRegistryValueAction_DWord_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The string that contains unexpanded references to environment variables, for example: %PATH%..
        /// </summary>
        internal static string SetRegistryValueAction_ExpandString_Description {
            get {
                return ResourceManager.GetString("SetRegistryValueAction_ExpandString_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        internal static string SetRegistryValueAction_ExpandString_FriendlyName {
            get {
                return ResourceManager.GetString("SetRegistryValueAction_ExpandString_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set registry value.
        /// </summary>
        internal static string SetRegistryValueAction_FriendlyName {
            get {
                return ResourceManager.GetString("SetRegistryValueAction_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type of registry value..
        /// </summary>
        internal static string SetRegistryValueAction_Kind_Description {
            get {
                return ResourceManager.GetString("SetRegistryValueAction_Kind_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value Type.
        /// </summary>
        internal static string SetRegistryValueAction_Kind_FriendlyName {
            get {
                return ResourceManager.GetString("SetRegistryValueAction_Kind_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The sequence of strings..
        /// </summary>
        internal static string SetRegistryValueAction_MultiString_Description {
            get {
                return ResourceManager.GetString("SetRegistryValueAction_MultiString_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        internal static string SetRegistryValueAction_MultiString_FriendlyName {
            get {
                return ResourceManager.GetString("SetRegistryValueAction_MultiString_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name of the registry value..
        /// </summary>
        internal static string SetRegistryValueAction_Name_Description {
            get {
                return ResourceManager.GetString("SetRegistryValueAction_Name_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string SetRegistryValueAction_Name_FriendlyName {
            get {
                return ResourceManager.GetString("SetRegistryValueAction_Name_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The full path to the registry key where the value is located..
        /// </summary>
        internal static string SetRegistryValueAction_Path_Description {
            get {
                return ResourceManager.GetString("SetRegistryValueAction_Path_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path.
        /// </summary>
        internal static string SetRegistryValueAction_Path_FriendlyName {
            get {
                return ResourceManager.GetString("SetRegistryValueAction_Path_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The 64-bit number..
        /// </summary>
        internal static string SetRegistryValueAction_QWord_Description {
            get {
                return ResourceManager.GetString("SetRegistryValueAction_QWord_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        internal static string SetRegistryValueAction_QWord_FriendlyName {
            get {
                return ResourceManager.GetString("SetRegistryValueAction_QWord_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The string..
        /// </summary>
        internal static string SetRegistryValueAction_String_Description {
            get {
                return ResourceManager.GetString("SetRegistryValueAction_String_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        internal static string SetRegistryValueAction_String_FriendlyName {
            get {
                return ResourceManager.GetString("SetRegistryValueAction_String_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Perform operations related to the Windows Registry..
        /// </summary>
        internal static string WindowsRegistry_Description {
            get {
                return ResourceManager.GetString("WindowsRegistry_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows Registry.
        /// </summary>
        internal static string WindowsRegistry_FriendlyName {
            get {
                return ResourceManager.GetString("WindowsRegistry_FriendlyName", resourceCulture);
            }
        }
    }
}
