//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PowerAutomate.Desktop.Modules.PostgreSQL.Actions.Properties {
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PowerAutomate.Desktop.Modules.PostgreSQL.Actions.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to PostgreSQL rejected the statement or the connection failed..
        /// </summary>
        public static string Error_DatabaseError_Description {
            get {
                return ResourceManager.GetString("Error_DatabaseError_Description", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to PostgreSQL error.
        /// </summary>
        public static string Error_DatabaseError_FriendlyName {
            get {
                return ResourceManager.GetString("Error_DatabaseError_FriendlyName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The connection string, SQL, timeout, or parameters are invalid..
        /// </summary>
        public static string Error_InvalidArgumentError_Description {
            get {
                return ResourceManager.GetString("Error_InvalidArgumentError_Description", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Invalid input.
        /// </summary>
        public static string Error_InvalidArgumentError_FriendlyName {
            get {
                return ResourceManager.GetString("Error_InvalidArgumentError_FriendlyName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Number of rows changed by the statement..
        /// </summary>
        public static string Execute_AffectedRows_Description {
            get {
                return ResourceManager.GetString("Execute_AffectedRows_Description", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Affected rows.
        /// </summary>
        public static string Execute_AffectedRows_FriendlyName {
            get {
                return ResourceManager.GetString("Execute_AffectedRows_FriendlyName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Npgsql connection string for the database..
        /// </summary>
        public static string Execute_ConnectionString_Description {
            get {
                return ResourceManager.GetString("Execute_ConnectionString_Description", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Connection string.
        /// </summary>
        public static string Execute_ConnectionString_FriendlyName {
            get {
                return ResourceManager.GetString("Execute_ConnectionString_FriendlyName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Execute a statement against PostgreSQL..
        /// </summary>
        public static string Execute_Description {
            get {
                return ResourceManager.GetString("Execute_Description", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Execute PostgreSQL statement.
        /// </summary>
        public static string Execute_FriendlyName {
            get {
                return ResourceManager.GetString("Execute_FriendlyName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Optional data table with Name and Value columns..
        /// </summary>
        public static string Execute_Parameters_Description {
            get {
                return ResourceManager.GetString("Execute_Parameters_Description", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Parameters.
        /// </summary>
        public static string Execute_Parameters_FriendlyName {
            get {
                return ResourceManager.GetString("Execute_Parameters_FriendlyName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to SQL with optional named parameter placeholders..
        /// </summary>
        public static string Execute_Sql_Description {
            get {
                return ResourceManager.GetString("Execute_Sql_Description", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to SQL statement.
        /// </summary>
        public static string Execute_Sql_FriendlyName {
            get {
                return ResourceManager.GetString("Execute_Sql_FriendlyName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Run a parameterized PostgreSQL statement..
        /// </summary>
        public static string Execute_Summary {
            get {
                return ResourceManager.GetString("Execute_Summary", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Maximum command execution time in seconds..
        /// </summary>
        public static string Execute_TimeoutSeconds_Description {
            get {
                return ResourceManager.GetString("Execute_TimeoutSeconds_Description", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Timeout in seconds.
        /// </summary>
        public static string Execute_TimeoutSeconds_FriendlyName {
            get {
                return ResourceManager.GetString("Execute_TimeoutSeconds_FriendlyName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Work with PostgreSQL using bound parameters..
        /// </summary>
        public static string PostgreSQL_Description {
            get {
                return ResourceManager.GetString("PostgreSQL_Description", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to PostgreSQL.
        /// </summary>
        public static string PostgreSQL_FriendlyName {
            get {
                return ResourceManager.GetString("PostgreSQL_FriendlyName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Npgsql connection string for the database..
        /// </summary>
        public static string Query_ConnectionString_Description {
            get {
                return ResourceManager.GetString("Query_ConnectionString_Description", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Connection string.
        /// </summary>
        public static string Query_ConnectionString_FriendlyName {
            get {
                return ResourceManager.GetString("Query_ConnectionString_FriendlyName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Read rows from a PostgreSQL database..
        /// </summary>
        public static string Query_Description {
            get {
                return ResourceManager.GetString("Query_Description", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Query PostgreSQL.
        /// </summary>
        public static string Query_FriendlyName {
            get {
                return ResourceManager.GetString("Query_FriendlyName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Optional data table with Name and Value columns..
        /// </summary>
        public static string Query_Parameters_Description {
            get {
                return ResourceManager.GetString("Query_Parameters_Description", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Parameters.
        /// </summary>
        public static string Query_Parameters_FriendlyName {
            get {
                return ResourceManager.GetString("Query_Parameters_FriendlyName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Rows returned by the query as a data table..
        /// </summary>
        public static string Query_Result_Description {
            get {
                return ResourceManager.GetString("Query_Result_Description", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Query result.
        /// </summary>
        public static string Query_Result_FriendlyName {
            get {
                return ResourceManager.GetString("Query_Result_FriendlyName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to SQL with optional named parameter placeholders..
        /// </summary>
        public static string Query_Sql_Description {
            get {
                return ResourceManager.GetString("Query_Sql_Description", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to SQL query.
        /// </summary>
        public static string Query_Sql_FriendlyName {
            get {
                return ResourceManager.GetString("Query_Sql_FriendlyName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Run a parameterized PostgreSQL query..
        /// </summary>
        public static string Query_Summary {
            get {
                return ResourceManager.GetString("Query_Summary", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Maximum command execution time in seconds..
        /// </summary>
        public static string Query_TimeoutSeconds_Description {
            get {
                return ResourceManager.GetString("Query_TimeoutSeconds_Description", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Timeout in seconds.
        /// </summary>
        public static string Query_TimeoutSeconds_FriendlyName {
            get {
                return ResourceManager.GetString("Query_TimeoutSeconds_FriendlyName", resourceCulture);
            }
        }
    }
}
