// ---------------------------------------------------
// Copyright (c) Jesus Fernandez. All Rights Reserved.
// ---------------------------------------------------

namespace PowerAutomate.Desktop.OpenTibia.Protocol.Opcodes;

/// <summary>
/// Client-to-server opcodes for protocol 8.60, matching the tfs-old-svn r3884 parsePacket dispatch.
/// </summary>
public enum ClientOpcode : byte
{
    None = 0x00,
    LoginServerRequest = 0x01,
    EnterGame = 0x0A,
    LeaveGame = 0x14,
    PingBack = 0x1E,
    AutoWalk = 0x64,
    WalkNorth = 0x65,
    WalkEast = 0x66,
    WalkSouth = 0x67,
    WalkWest = 0x68,
    Stop = 0x69,
    WalkNorthEast = 0x6A,
    WalkSouthEast = 0x6B,
    WalkSouthWest = 0x6C,
    WalkNorthWest = 0x6D,
    TurnNorth = 0x6F,
    TurnEast = 0x70,
    TurnSouth = 0x71,
    TurnWest = 0x72,
    Move = 0x78,
    InspectNpcTrade = 0x79,
    BuyItem = 0x7A,
    SellItem = 0x7B,
    CloseNpcTrade = 0x7C,
    RequestTrade = 0x7D,
    InspectTrade = 0x7E,
    AcceptTrade = 0x7F,
    RejectTrade = 0x80,
    UseItem = 0x82,
    UseItemWith = 0x83,
    UseOnCreature = 0x84,
    RotateItem = 0x85,
    CloseContainer = 0x87,
    UpContainer = 0x88,
    EditText = 0x89,
    EditList = 0x8A,
    Look = 0x8C,
    Talk = 0x96,
    RequestChannels = 0x97,
    JoinChannel = 0x98,
    LeaveChannel = 0x99,
    OpenPrivateChannel = 0x9A,
    OpenRuleViolation = 0x9B,
    CloseRuleViolation = 0x9C,
    CancelRuleViolation = 0x9D,
    CloseNpcChannel = 0x9E,
    ChangeFightModes = 0xA0,
    Attack = 0xA1,
    Follow = 0xA2,
    InviteToParty = 0xA3,
    JoinParty = 0xA4,
    RevokeInvitation = 0xA5,
    PassLeadership = 0xA6,
    LeaveParty = 0xA7,
    ShareExperience = 0xA8,
    OpenOwnChannel = 0xAA,
    InviteToOwnChannel = 0xAB,
    ExcludeFromOwnChannel = 0xAC,
    CancelAttackAndFollow = 0xBE,
    UpdateTile = 0xC9,
    RefreshContainer = 0xCA,
    RequestOutfit = 0xD2,
    ChangeOutfit = 0xD3,
    AddVip = 0xDC,
    RemoveVip = 0xDD,
    BugReport = 0xE6,
    RuleViolation = 0xE7,
    DebugReport = 0xE8,
    RequestQuestLog = 0xF0,
    RequestQuestLine = 0xF1,
    NewRuleViolation = 0xF2
}
