//-------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------

namespace PowerAutomate.Desktop.Modules.OpenTibia.Actions.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PowerAutomate.Desktop.Modules.OpenTibia.Actions.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The id of the creature to attack..
        /// </summary>
        public static string Attack_CreatureId_Description {
            get {
                return ResourceManager.GetString("Attack_CreatureId_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creature ID.
        /// </summary>
        public static string Attack_CreatureId_FriendlyName {
            get {
                return ResourceManager.GetString("Attack_CreatureId_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attacks the given creature..
        /// </summary>
        public static string Attack_Description {
            get {
                return ResourceManager.GetString("Attack_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attack.
        /// </summary>
        public static string Attack_FriendlyName {
            get {
                return ResourceManager.GetString("Attack_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The session returned by Enter game..
        /// </summary>
        public static string Attack_GameSession_Description {
            get {
                return ResourceManager.GetString("Attack_GameSession_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game session.
        /// </summary>
        public static string Attack_GameSession_FriendlyName {
            get {
                return ResourceManager.GetString("Attack_GameSession_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attack a creature..
        /// </summary>
        public static string Attack_Summary {
            get {
                return ResourceManager.GetString("Attack_Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Walks an ordered path of one or more steps..
        /// </summary>
        public static string AutoWalk_Description {
            get {
                return ResourceManager.GetString("AutoWalk_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The ordered steps to walk, one at a time..
        /// </summary>
        public static string AutoWalk_Directions_Description {
            get {
                return ResourceManager.GetString("AutoWalk_Directions_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directions.
        /// </summary>
        public static string AutoWalk_Directions_FriendlyName {
            get {
                return ResourceManager.GetString("AutoWalk_Directions_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto walk.
        /// </summary>
        public static string AutoWalk_FriendlyName {
            get {
                return ResourceManager.GetString("AutoWalk_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The session returned by Enter game..
        /// </summary>
        public static string AutoWalk_GameSession_Description {
            get {
                return ResourceManager.GetString("AutoWalk_GameSession_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game session.
        /// </summary>
        public static string AutoWalk_GameSession_FriendlyName {
            get {
                return ResourceManager.GetString("AutoWalk_GameSession_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Walk a path automatically..
        /// </summary>
        public static string AutoWalk_Summary {
            get {
                return ResourceManager.GetString("AutoWalk_Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log into and out of the account server..
        /// </summary>
        public static string Category_Authentication_Description {
            get {
                return ResourceManager.GetString("Category_Authentication_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authentication.
        /// </summary>
        public static string Category_Authentication_FriendlyName {
            get {
                return ResourceManager.GetString("Category_Authentication_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List and select characters on the account..
        /// </summary>
        public static string Category_Characters_Description {
            get {
                return ResourceManager.GetString("Category_Characters_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Characters.
        /// </summary>
        public static string Category_Characters_FriendlyName {
            get {
                return ResourceManager.GetString("Category_Characters_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send messages from the client to the game server..
        /// </summary>
        public static string Category_ClientMessages_Description {
            get {
                return ResourceManager.GetString("Category_ClientMessages_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client Messages.
        /// </summary>
        public static string Category_ClientMessages_FriendlyName {
            get {
                return ResourceManager.GetString("Category_ClientMessages_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter, exit and monitor a game session..
        /// </summary>
        public static string Category_Game_Description {
            get {
                return ResourceManager.GetString("Category_Game_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game.
        /// </summary>
        public static string Category_Game_FriendlyName {
            get {
                return ResourceManager.GetString("Category_Game_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receive and inspect messages from the game server..
        /// </summary>
        public static string Category_ServerMessages_Description {
            get {
                return ResourceManager.GetString("Category_ServerMessages_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server Messages.
        /// </summary>
        public static string Category_ServerMessages_FriendlyName {
            get {
                return ResourceManager.GetString("Category_ServerMessages_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number of messages discarded..
        /// </summary>
        public static string ClearServerMessages_Cleared_Description {
            get {
                return ResourceManager.GetString("ClearServerMessages_Cleared_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cleared.
        /// </summary>
        public static string ClearServerMessages_Cleared_FriendlyName {
            get {
                return ResourceManager.GetString("ClearServerMessages_Cleared_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discards every message currently queued..
        /// </summary>
        public static string ClearServerMessages_Description {
            get {
                return ResourceManager.GetString("ClearServerMessages_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear server messages.
        /// </summary>
        public static string ClearServerMessages_FriendlyName {
            get {
                return ResourceManager.GetString("ClearServerMessages_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The session returned by Enter game..
        /// </summary>
        public static string ClearServerMessages_GameSession_Description {
            get {
                return ResourceManager.GetString("ClearServerMessages_GameSession_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game session.
        /// </summary>
        public static string ClearServerMessages_GameSession_FriendlyName {
            get {
                return ResourceManager.GetString("ClearServerMessages_GameSession_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear the server message queue..
        /// </summary>
        public static string ClearServerMessages_Summary {
            get {
                return ResourceManager.GetString("ClearServerMessages_Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Force-closes the connection; safe to call repeatedly and after a fault..
        /// </summary>
        public static string Disconnect_Description {
            get {
                return ResourceManager.GetString("Disconnect_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disconnect.
        /// </summary>
        public static string Disconnect_FriendlyName {
            get {
                return ResourceManager.GetString("Disconnect_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The session returned by Enter game..
        /// </summary>
        public static string Disconnect_GameSession_Description {
            get {
                return ResourceManager.GetString("Disconnect_GameSession_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game session.
        /// </summary>
        public static string Disconnect_GameSession_FriendlyName {
            get {
                return ResourceManager.GetString("Disconnect_GameSession_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Force-close the game connection..
        /// </summary>
        public static string Disconnect_Summary {
            get {
                return ResourceManager.GetString("Disconnect_Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The character to enter the game with..
        /// </summary>
        public static string EnterGame_Character_Description {
            get {
                return ResourceManager.GetString("EnterGame_Character_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Character.
        /// </summary>
        public static string EnterGame_Character_FriendlyName {
            get {
                return ResourceManager.GetString("EnterGame_Character_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connects to the game server and enters the world with the selected character..
        /// </summary>
        public static string EnterGame_Description {
            get {
                return ResourceManager.GetString("EnterGame_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter game.
        /// </summary>
        public static string EnterGame_FriendlyName {
            get {
                return ResourceManager.GetString("EnterGame_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The session to pass to later actions..
        /// </summary>
        public static string EnterGame_GameSession_Description {
            get {
                return ResourceManager.GetString("EnterGame_GameSession_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game session.
        /// </summary>
        public static string EnterGame_GameSession_FriendlyName {
            get {
                return ResourceManager.GetString("EnterGame_GameSession_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The session returned by Login..
        /// </summary>
        public static string EnterGame_LoginSession_Description {
            get {
                return ResourceManager.GetString("EnterGame_LoginSession_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login session.
        /// </summary>
        public static string EnterGame_LoginSession_FriendlyName {
            get {
                return ResourceManager.GetString("EnterGame_LoginSession_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The maximum number of server messages buffered at once..
        /// </summary>
        public static string EnterGame_QueueCapacity_Description {
            get {
                return ResourceManager.GetString("EnterGame_QueueCapacity_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Queue capacity.
        /// </summary>
        public static string EnterGame_QueueCapacity_FriendlyName {
            get {
                return ResourceManager.GetString("EnterGame_QueueCapacity_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the game with a character..
        /// </summary>
        public static string EnterGame_Summary {
            get {
                return ResourceManager.GetString("EnterGame_Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How long to wait for the game server to confirm entry, in milliseconds..
        /// </summary>
        public static string EnterGame_TimeoutMs_Description {
            get {
                return ResourceManager.GetString("EnterGame_TimeoutMs_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timeout (ms).
        /// </summary>
        public static string EnterGame_TimeoutMs_FriendlyName {
            get {
                return ResourceManager.GetString("EnterGame_TimeoutMs_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The session is already connected..
        /// </summary>
        public static string Error_AlreadyConnectedError_Description {
            get {
                return ResourceManager.GetString("Error_AlreadyConnectedError_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Already connected.
        /// </summary>
        public static string Error_AlreadyConnectedError_FriendlyName {
            get {
                return ResourceManager.GetString("Error_AlreadyConnectedError_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The server rejected the supplied credentials..
        /// </summary>
        public static string Error_AuthenticationFailedError_Description {
            get {
                return ResourceManager.GetString("Error_AuthenticationFailedError_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authentication failed.
        /// </summary>
        public static string Error_AuthenticationFailedError_FriendlyName {
            get {
                return ResourceManager.GetString("Error_AuthenticationFailedError_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The requested character is not on the account..
        /// </summary>
        public static string Error_CharacterNotFoundError_Description {
            get {
                return ResourceManager.GetString("Error_CharacterNotFoundError_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Character not found.
        /// </summary>
        public static string Error_CharacterNotFoundError_FriendlyName {
            get {
                return ResourceManager.GetString("Error_CharacterNotFoundError_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The socket could not connect to the server..
        /// </summary>
        public static string Error_ConnectionFailedError_Description {
            get {
                return ResourceManager.GetString("Error_ConnectionFailedError_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection failed.
        /// </summary>
        public static string Error_ConnectionFailedError_FriendlyName {
            get {
                return ResourceManager.GetString("Error_ConnectionFailedError_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An input value was missing or out of range..
        /// </summary>
        public static string Error_InvalidArgumentError_Description {
            get {
                return ResourceManager.GetString("Error_InvalidArgumentError_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid argument.
        /// </summary>
        public static string Error_InvalidArgumentError_FriendlyName {
            get {
                return ResourceManager.GetString("Error_InvalidArgumentError_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No active session is available for this action..
        /// </summary>
        public static string Error_NotConnectedError_Description {
            get {
                return ResourceManager.GetString("Error_NotConnectedError_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not connected.
        /// </summary>
        public static string Error_NotConnectedError_FriendlyName {
            get {
                return ResourceManager.GetString("Error_NotConnectedError_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The server sent a message the client could not process..
        /// </summary>
        public static string Error_ProtocolErrorError_Description {
            get {
                return ResourceManager.GetString("Error_ProtocolErrorError_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Protocol error.
        /// </summary>
        public static string Error_ProtocolErrorError_FriendlyName {
            get {
                return ResourceManager.GetString("Error_ProtocolErrorError_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The server did not respond in time..
        /// </summary>
        public static string Error_TimeoutError_Description {
            get {
                return ResourceManager.GetString("Error_TimeoutError_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timeout.
        /// </summary>
        public static string Error_TimeoutError_FriendlyName {
            get {
                return ResourceManager.GetString("Error_TimeoutError_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected failure occurred..
        /// </summary>
        public static string Error_UnknownError_Description {
            get {
                return ResourceManager.GetString("Error_UnknownError_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown error.
        /// </summary>
        public static string Error_UnknownError_FriendlyName {
            get {
                return ResourceManager.GetString("Error_UnknownError_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sends a graceful logout and disconnects from the game server..
        /// </summary>
        public static string ExitGame_Description {
            get {
                return ResourceManager.GetString("ExitGame_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit game.
        /// </summary>
        public static string ExitGame_FriendlyName {
            get {
                return ResourceManager.GetString("ExitGame_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The session returned by Enter game..
        /// </summary>
        public static string ExitGame_GameSession_Description {
            get {
                return ResourceManager.GetString("ExitGame_GameSession_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game session.
        /// </summary>
        public static string ExitGame_GameSession_FriendlyName {
            get {
                return ResourceManager.GetString("ExitGame_GameSession_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit the game..
        /// </summary>
        public static string ExitGame_Summary {
            get {
                return ResourceManager.GetString("ExitGame_Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The characters available on the account..
        /// </summary>
        public static string GetCharacterList_Characters_Description {
            get {
                return ResourceManager.GetString("GetCharacterList_Characters_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Characters.
        /// </summary>
        public static string GetCharacterList_Characters_FriendlyName {
            get {
                return ResourceManager.GetString("GetCharacterList_Characters_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Returns the characters available on the login session's account..
        /// </summary>
        public static string GetCharacterList_Description {
            get {
                return ResourceManager.GetString("GetCharacterList_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get character list.
        /// </summary>
        public static string GetCharacterList_FriendlyName {
            get {
                return ResourceManager.GetString("GetCharacterList_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The session returned by Login..
        /// </summary>
        public static string GetCharacterList_LoginSession_Description {
            get {
                return ResourceManager.GetString("GetCharacterList_LoginSession_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login session.
        /// </summary>
        public static string GetCharacterList_LoginSession_FriendlyName {
            get {
                return ResourceManager.GetString("GetCharacterList_LoginSession_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get the account's character list..
        /// </summary>
        public static string GetCharacterList_Summary {
            get {
                return ResourceManager.GetString("GetCharacterList_Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The maximum number of messages the queue can hold..
        /// </summary>
        public static string GetStreamStatistics_Capacity_Description {
            get {
                return ResourceManager.GetString("GetStreamStatistics_Capacity_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capacity.
        /// </summary>
        public static string GetStreamStatistics_Capacity_FriendlyName {
            get {
                return ResourceManager.GetString("GetStreamStatistics_Capacity_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number of messages currently queued..
        /// </summary>
        public static string GetStreamStatistics_Depth_Description {
            get {
                return ResourceManager.GetString("GetStreamStatistics_Depth_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Depth.
        /// </summary>
        public static string GetStreamStatistics_Depth_FriendlyName {
            get {
                return ResourceManager.GetString("GetStreamStatistics_Depth_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The total number of messages ever dequeued..
        /// </summary>
        public static string GetStreamStatistics_Dequeued_Description {
            get {
                return ResourceManager.GetString("GetStreamStatistics_Dequeued_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dequeued.
        /// </summary>
        public static string GetStreamStatistics_Dequeued_FriendlyName {
            get {
                return ResourceManager.GetString("GetStreamStatistics_Dequeued_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Returns point-in-time counters for the inbound message queue..
        /// </summary>
        public static string GetStreamStatistics_Description {
            get {
                return ResourceManager.GetString("GetStreamStatistics_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Messages discarded because the queue was full..
        /// </summary>
        public static string GetStreamStatistics_Dropped_Description {
            get {
                return ResourceManager.GetString("GetStreamStatistics_Dropped_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dropped.
        /// </summary>
        public static string GetStreamStatistics_Dropped_FriendlyName {
            get {
                return ResourceManager.GetString("GetStreamStatistics_Dropped_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The total number of messages ever enqueued..
        /// </summary>
        public static string GetStreamStatistics_Enqueued_Description {
            get {
                return ResourceManager.GetString("GetStreamStatistics_Enqueued_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enqueued.
        /// </summary>
        public static string GetStreamStatistics_Enqueued_FriendlyName {
            get {
                return ResourceManager.GetString("GetStreamStatistics_Enqueued_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Messages discarded because their opcode was not subscribed..
        /// </summary>
        public static string GetStreamStatistics_Filtered_Description {
            get {
                return ResourceManager.GetString("GetStreamStatistics_Filtered_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filtered.
        /// </summary>
        public static string GetStreamStatistics_Filtered_FriendlyName {
            get {
                return ResourceManager.GetString("GetStreamStatistics_Filtered_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get stream statistics.
        /// </summary>
        public static string GetStreamStatistics_FriendlyName {
            get {
                return ResourceManager.GetString("GetStreamStatistics_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The session returned by Enter game..
        /// </summary>
        public static string GetStreamStatistics_GameSession_Description {
            get {
                return ResourceManager.GetString("GetStreamStatistics_GameSession_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game session.
        /// </summary>
        public static string GetStreamStatistics_GameSession_FriendlyName {
            get {
                return ResourceManager.GetString("GetStreamStatistics_GameSession_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The highest depth the queue has reached..
        /// </summary>
        public static string GetStreamStatistics_MaxDepthSeen_Description {
            get {
                return ResourceManager.GetString("GetStreamStatistics_MaxDepthSeen_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max depth seen.
        /// </summary>
        public static string GetStreamStatistics_MaxDepthSeen_FriendlyName {
            get {
                return ResourceManager.GetString("GetStreamStatistics_MaxDepthSeen_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get server message queue statistics..
        /// </summary>
        public static string GetStreamStatistics_Summary {
            get {
                return ResourceManager.GetString("GetStreamStatistics_Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Secondary arguments for fine-tuning..
        /// </summary>
        public static string Group_Advanced_Description {
            get {
                return ResourceManager.GetString("Group_Advanced_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced.
        /// </summary>
        public static string Group_Advanced_FriendlyName {
            get {
                return ResourceManager.GetString("Group_Advanced_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The main arguments needed for common use..
        /// </summary>
        public static string Group_General_Description {
            get {
                return ResourceManager.GetString("Group_General_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        public static string Group_General_FriendlyName {
            get {
                return ResourceManager.GetString("Group_General_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arguments identifying who or what the action affects..
        /// </summary>
        public static string Group_Target_Description {
            get {
                return ResourceManager.GetString("Group_Target_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target.
        /// </summary>
        public static string Group_Target_FriendlyName {
            get {
                return ResourceManager.GetString("Group_Target_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A single-shot, non-blocking peek at whether a message is queued..
        /// </summary>
        public static string HasServerMessage_Description {
            get {
                return ResourceManager.GetString("HasServerMessage_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Has server message.
        /// </summary>
        public static string HasServerMessage_FriendlyName {
            get {
                return ResourceManager.GetString("HasServerMessage_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The session returned by Enter game..
        /// </summary>
        public static string HasServerMessage_GameSession_Description {
            get {
                return ResourceManager.GetString("HasServerMessage_GameSession_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game session.
        /// </summary>
        public static string HasServerMessage_GameSession_FriendlyName {
            get {
                return ResourceManager.GetString("HasServerMessage_GameSession_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to True while at least one message is queued..
        /// </summary>
        public static string HasServerMessage_HasMessage_Description {
            get {
                return ResourceManager.GetString("HasServerMessage_HasMessage_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Has message.
        /// </summary>
        public static string HasServerMessage_HasMessage_FriendlyName {
            get {
                return ResourceManager.GetString("HasServerMessage_HasMessage_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check whether a server message is waiting..
        /// </summary>
        public static string HasServerMessage_Summary {
            get {
                return ResourceManager.GetString("HasServerMessage_Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checks whether the game session is connected and not faulted..
        /// </summary>
        public static string IsInGame_Description {
            get {
                return ResourceManager.GetString("IsInGame_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is in game.
        /// </summary>
        public static string IsInGame_FriendlyName {
            get {
                return ResourceManager.GetString("IsInGame_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The session returned by Enter game..
        /// </summary>
        public static string IsInGame_GameSession_Description {
            get {
                return ResourceManager.GetString("IsInGame_GameSession_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game session.
        /// </summary>
        public static string IsInGame_GameSession_FriendlyName {
            get {
                return ResourceManager.GetString("IsInGame_GameSession_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to True while the session is connected and in game..
        /// </summary>
        public static string IsInGame_IsInGame_Description {
            get {
                return ResourceManager.GetString("IsInGame_IsInGame_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is in game.
        /// </summary>
        public static string IsInGame_IsInGame_FriendlyName {
            get {
                return ResourceManager.GetString("IsInGame_IsInGame_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check whether the session is in game..
        /// </summary>
        public static string IsInGame_Summary {
            get {
                return ResourceManager.GetString("IsInGame_Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The account name to authenticate with..
        /// </summary>
        public static string Login_AccountName_Description {
            get {
                return ResourceManager.GetString("Login_AccountName_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account name.
        /// </summary>
        public static string Login_AccountName_FriendlyName {
            get {
                return ResourceManager.GetString("Login_AccountName_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The characters available on the account..
        /// </summary>
        public static string Login_Characters_Description {
            get {
                return ResourceManager.GetString("Login_Characters_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Characters.
        /// </summary>
        public static string Login_Characters_FriendlyName {
            get {
                return ResourceManager.GetString("Login_Characters_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authenticates against the login server and lists the account's characters..
        /// </summary>
        public static string Login_Description {
            get {
                return ResourceManager.GetString("Login_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Login_FriendlyName {
            get {
                return ResourceManager.GetString("Login_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The login server's hostname or IP address..
        /// </summary>
        public static string Login_Host_Description {
            get {
                return ResourceManager.GetString("Login_Host_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Host.
        /// </summary>
        public static string Login_Host_FriendlyName {
            get {
                return ResourceManager.GetString("Login_Host_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The session to pass to later actions..
        /// </summary>
        public static string Login_LoginSession_Description {
            get {
                return ResourceManager.GetString("Login_LoginSession_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login session.
        /// </summary>
        public static string Login_LoginSession_FriendlyName {
            get {
                return ResourceManager.GetString("Login_LoginSession_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The server's message of the day..
        /// </summary>
        public static string Login_Motd_Description {
            get {
                return ResourceManager.GetString("Login_Motd_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message of the day.
        /// </summary>
        public static string Login_Motd_FriendlyName {
            get {
                return ResourceManager.GetString("Login_Motd_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The account password..
        /// </summary>
        public static string Login_Password_Description {
            get {
                return ResourceManager.GetString("Login_Password_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Login_Password_FriendlyName {
            get {
                return ResourceManager.GetString("Login_Password_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The login server's TCP port..
        /// </summary>
        public static string Login_Port_Description {
            get {
                return ResourceManager.GetString("Login_Port_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port.
        /// </summary>
        public static string Login_Port_FriendlyName {
            get {
                return ResourceManager.GetString("Login_Port_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log into the account server..
        /// </summary>
        public static string Login_Summary {
            get {
                return ResourceManager.GetString("Login_Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How long to wait for the server to answer, in milliseconds..
        /// </summary>
        public static string Login_TimeoutMs_Description {
            get {
                return ResourceManager.GetString("Login_TimeoutMs_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timeout (ms).
        /// </summary>
        public static string Login_TimeoutMs_FriendlyName {
            get {
                return ResourceManager.GetString("Login_TimeoutMs_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closes a login session's socket; calling it twice is a no-op..
        /// </summary>
        public static string Logout_Description {
            get {
                return ResourceManager.GetString("Logout_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        public static string Logout_FriendlyName {
            get {
                return ResourceManager.GetString("Logout_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The session returned by Login..
        /// </summary>
        public static string Logout_LoginSession_Description {
            get {
                return ResourceManager.GetString("Logout_LoginSession_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login session.
        /// </summary>
        public static string Logout_LoginSession_FriendlyName {
            get {
                return ResourceManager.GetString("Logout_LoginSession_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log out of the account server..
        /// </summary>
        public static string Logout_Summary {
            get {
                return ResourceManager.GetString("Logout_Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Looks at an item at the given map position..
        /// </summary>
        public static string Look_Description {
            get {
                return ResourceManager.GetString("Look_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Look.
        /// </summary>
        public static string Look_FriendlyName {
            get {
                return ResourceManager.GetString("Look_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The session returned by Enter game..
        /// </summary>
        public static string Look_GameSession_Description {
            get {
                return ResourceManager.GetString("Look_GameSession_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game session.
        /// </summary>
        public static string Look_GameSession_FriendlyName {
            get {
                return ResourceManager.GetString("Look_GameSession_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The item's server id..
        /// </summary>
        public static string Look_ItemId_Description {
            get {
                return ResourceManager.GetString("Look_ItemId_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item ID.
        /// </summary>
        public static string Look_ItemId_FriendlyName {
            get {
                return ResourceManager.GetString("Look_ItemId_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The item's position within the tile stack..
        /// </summary>
        public static string Look_StackPosition_Description {
            get {
                return ResourceManager.GetString("Look_StackPosition_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stack position.
        /// </summary>
        public static string Look_StackPosition_FriendlyName {
            get {
                return ResourceManager.GetString("Look_StackPosition_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Look at an item..
        /// </summary>
        public static string Look_Summary {
            get {
                return ResourceManager.GetString("Look_Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The item's X map coordinate..
        /// </summary>
        public static string Look_X_Description {
            get {
                return ResourceManager.GetString("Look_X_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to X.
        /// </summary>
        public static string Look_X_FriendlyName {
            get {
                return ResourceManager.GetString("Look_X_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The item's Y map coordinate..
        /// </summary>
        public static string Look_Y_Description {
            get {
                return ResourceManager.GetString("Look_Y_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Y.
        /// </summary>
        public static string Look_Y_FriendlyName {
            get {
                return ResourceManager.GetString("Look_Y_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The item's floor (Z) coordinate..
        /// </summary>
        public static string Look_Z_Description {
            get {
                return ResourceManager.GetString("Look_Z_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Z.
        /// </summary>
        public static string Look_Z_FriendlyName {
            get {
                return ResourceManager.GetString("Look_Z_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Takes a single step in the given direction..
        /// </summary>
        public static string Move_Description {
            get {
                return ResourceManager.GetString("Move_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The direction to step toward..
        /// </summary>
        public static string Move_Direction_Description {
            get {
                return ResourceManager.GetString("Move_Direction_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Direction.
        /// </summary>
        public static string Move_Direction_FriendlyName {
            get {
                return ResourceManager.GetString("Move_Direction_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move.
        /// </summary>
        public static string Move_FriendlyName {
            get {
                return ResourceManager.GetString("Move_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The session returned by Enter game..
        /// </summary>
        public static string Move_GameSession_Description {
            get {
                return ResourceManager.GetString("Move_GameSession_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game session.
        /// </summary>
        public static string Move_GameSession_FriendlyName {
            get {
                return ResourceManager.GetString("Move_GameSession_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Take a step..
        /// </summary>
        public static string Move_Summary {
            get {
                return ResourceManager.GetString("Move_Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect to and play on an OpenTibia 8.60 game server..
        /// </summary>
        public static string OpenTibia_Description {
            get {
                return ResourceManager.GetString("OpenTibia_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OpenTibia.
        /// </summary>
        public static string OpenTibia_FriendlyName {
            get {
                return ResourceManager.GetString("OpenTibia_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number of messages received..
        /// </summary>
        public static string ReceiveServerMessages_Count_Description {
            get {
                return ResourceManager.GetString("ReceiveServerMessages_Count_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Count.
        /// </summary>
        public static string ReceiveServerMessages_Count_FriendlyName {
            get {
                return ResourceManager.GetString("ReceiveServerMessages_Count_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drains a bounded batch of messages from the inbound queue..
        /// </summary>
        public static string ReceiveServerMessages_Description {
            get {
                return ResourceManager.GetString("ReceiveServerMessages_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receive server messages.
        /// </summary>
        public static string ReceiveServerMessages_FriendlyName {
            get {
                return ResourceManager.GetString("ReceiveServerMessages_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The session returned by Enter game..
        /// </summary>
        public static string ReceiveServerMessages_GameSession_Description {
            get {
                return ResourceManager.GetString("ReceiveServerMessages_GameSession_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game session.
        /// </summary>
        public static string ReceiveServerMessages_GameSession_FriendlyName {
            get {
                return ResourceManager.GetString("ReceiveServerMessages_GameSession_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The maximum number of messages to return..
        /// </summary>
        public static string ReceiveServerMessages_MaxCount_Description {
            get {
                return ResourceManager.GetString("ReceiveServerMessages_MaxCount_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max count.
        /// </summary>
        public static string ReceiveServerMessages_MaxCount_FriendlyName {
            get {
                return ResourceManager.GetString("ReceiveServerMessages_MaxCount_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The messages received during this call..
        /// </summary>
        public static string ReceiveServerMessages_Messages_Description {
            get {
                return ResourceManager.GetString("ReceiveServerMessages_Messages_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Messages.
        /// </summary>
        public static string ReceiveServerMessages_Messages_FriendlyName {
            get {
                return ResourceManager.GetString("ReceiveServerMessages_Messages_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How long to wait for the first message, clamped to 1000 ms..
        /// </summary>
        public static string ReceiveServerMessages_SliceTimeoutMs_Description {
            get {
                return ResourceManager.GetString("ReceiveServerMessages_SliceTimeoutMs_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slice timeout (ms).
        /// </summary>
        public static string ReceiveServerMessages_SliceTimeoutMs_FriendlyName {
            get {
                return ResourceManager.GetString("ReceiveServerMessages_SliceTimeoutMs_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receive server messages..
        /// </summary>
        public static string ReceiveServerMessages_Summary {
            get {
                return ResourceManager.GetString("ReceiveServerMessages_Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to True when no message arrived within the slice..
        /// </summary>
        public static string ReceiveServerMessages_TimedOut_Description {
            get {
                return ResourceManager.GetString("ReceiveServerMessages_TimedOut_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timed out.
        /// </summary>
        public static string ReceiveServerMessages_TimedOut_FriendlyName {
            get {
                return ResourceManager.GetString("ReceiveServerMessages_TimedOut_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name of the character to select..
        /// </summary>
        public static string SelectCharacter_CharacterName_Description {
            get {
                return ResourceManager.GetString("SelectCharacter_CharacterName_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Character name.
        /// </summary>
        public static string SelectCharacter_CharacterName_FriendlyName {
            get {
                return ResourceManager.GetString("SelectCharacter_CharacterName_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected character..
        /// </summary>
        public static string SelectCharacter_Character_Description {
            get {
                return ResourceManager.GetString("SelectCharacter_Character_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Character.
        /// </summary>
        public static string SelectCharacter_Character_FriendlyName {
            get {
                return ResourceManager.GetString("SelectCharacter_Character_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finds a character by name among the account's characters..
        /// </summary>
        public static string SelectCharacter_Description {
            get {
                return ResourceManager.GetString("SelectCharacter_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select character.
        /// </summary>
        public static string SelectCharacter_FriendlyName {
            get {
                return ResourceManager.GetString("SelectCharacter_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The session returned by Login..
        /// </summary>
        public static string SelectCharacter_LoginSession_Description {
            get {
                return ResourceManager.GetString("SelectCharacter_LoginSession_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login session.
        /// </summary>
        public static string SelectCharacter_LoginSession_FriendlyName {
            get {
                return ResourceManager.GetString("SelectCharacter_LoginSession_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a character by name..
        /// </summary>
        public static string SelectCharacter_Summary {
            get {
                return ResourceManager.GetString("SelectCharacter_Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sends a raw opcode and hex-encoded payload not otherwise modelled..
        /// </summary>
        public static string SendClientMessage_Description {
            get {
                return ResourceManager.GetString("SendClientMessage_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send client message.
        /// </summary>
        public static string SendClientMessage_FriendlyName {
            get {
                return ResourceManager.GetString("SendClientMessage_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The session returned by Enter game..
        /// </summary>
        public static string SendClientMessage_GameSession_Description {
            get {
                return ResourceManager.GetString("SendClientMessage_GameSession_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game session.
        /// </summary>
        public static string SendClientMessage_GameSession_FriendlyName {
            get {
                return ResourceManager.GetString("SendClientMessage_GameSession_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The message opcode, from 0 to 255..
        /// </summary>
        public static string SendClientMessage_Opcode_Description {
            get {
                return ResourceManager.GetString("SendClientMessage_Opcode_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opcode.
        /// </summary>
        public static string SendClientMessage_Opcode_FriendlyName {
            get {
                return ResourceManager.GetString("SendClientMessage_Opcode_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The message body as an even-length hex string..
        /// </summary>
        public static string SendClientMessage_PayloadHex_Description {
            get {
                return ResourceManager.GetString("SendClientMessage_PayloadHex_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payload (hex).
        /// </summary>
        public static string SendClientMessage_PayloadHex_FriendlyName {
            get {
                return ResourceManager.GetString("SendClientMessage_PayloadHex_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send a raw client message..
        /// </summary>
        public static string SendClientMessage_Summary {
            get {
                return ResourceManager.GetString("SendClientMessage_Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The target channel id, required for channel messages..
        /// </summary>
        public static string SendTalk_ChannelId_Description {
            get {
                return ResourceManager.GetString("SendTalk_ChannelId_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Channel ID.
        /// </summary>
        public static string SendTalk_ChannelId_FriendlyName {
            get {
                return ResourceManager.GetString("SendTalk_ChannelId_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sends a chat message of the given speak type..
        /// </summary>
        public static string SendTalk_Description {
            get {
                return ResourceManager.GetString("SendTalk_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send talk.
        /// </summary>
        public static string SendTalk_FriendlyName {
            get {
                return ResourceManager.GetString("SendTalk_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The session returned by Enter game..
        /// </summary>
        public static string SendTalk_GameSession_Description {
            get {
                return ResourceManager.GetString("SendTalk_GameSession_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game session.
        /// </summary>
        public static string SendTalk_GameSession_FriendlyName {
            get {
                return ResourceManager.GetString("SendTalk_GameSession_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The recipient's name, required for private messages..
        /// </summary>
        public static string SendTalk_ReceiverName_Description {
            get {
                return ResourceManager.GetString("SendTalk_ReceiverName_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receiver name.
        /// </summary>
        public static string SendTalk_ReceiverName_FriendlyName {
            get {
                return ResourceManager.GetString("SendTalk_ReceiverName_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send a chat message..
        /// </summary>
        public static string SendTalk_Summary {
            get {
                return ResourceManager.GetString("SendTalk_Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The message text..
        /// </summary>
        public static string SendTalk_Text_Description {
            get {
                return ResourceManager.GetString("SendTalk_Text_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text.
        /// </summary>
        public static string SendTalk_Text_FriendlyName {
            get {
                return ResourceManager.GetString("SendTalk_Text_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The kind of chat message to send..
        /// </summary>
        public static string SendTalk_Type_Description {
            get {
                return ResourceManager.GetString("SendTalk_Type_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speak type.
        /// </summary>
        public static string SendTalk_Type_FriendlyName {
            get {
                return ResourceManager.GetString("SendTalk_Type_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restricts the inbound queue to a set of opcodes; empty clears the restriction..
        /// </summary>
        public static string SubscribeOpcodes_Description {
            get {
                return ResourceManager.GetString("SubscribeOpcodes_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscribe opcodes.
        /// </summary>
        public static string SubscribeOpcodes_FriendlyName {
            get {
                return ResourceManager.GetString("SubscribeOpcodes_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The session returned by Enter game..
        /// </summary>
        public static string SubscribeOpcodes_GameSession_Description {
            get {
                return ResourceManager.GetString("SubscribeOpcodes_GameSession_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game session.
        /// </summary>
        public static string SubscribeOpcodes_GameSession_FriendlyName {
            get {
                return ResourceManager.GetString("SubscribeOpcodes_GameSession_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The opcodes to allow; empty or omitted allows all opcodes..
        /// </summary>
        public static string SubscribeOpcodes_Opcodes_Description {
            get {
                return ResourceManager.GetString("SubscribeOpcodes_Opcodes_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opcodes.
        /// </summary>
        public static string SubscribeOpcodes_Opcodes_FriendlyName {
            get {
                return ResourceManager.GetString("SubscribeOpcodes_Opcodes_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restrict which opcodes are queued..
        /// </summary>
        public static string SubscribeOpcodes_Summary {
            get {
                return ResourceManager.GetString("SubscribeOpcodes_Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tibia character.
        /// </summary>
        public static string TibiaCharacter_FriendlyName {
            get {
                return ResourceManager.GetString("TibiaCharacter_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tibia characters.
        /// </summary>
        public static string TibiaCharacter_FriendlyNamePlural {
            get {
                return ResourceManager.GetString("TibiaCharacter_FriendlyNamePlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tibia game session.
        /// </summary>
        public static string TibiaGameSession_FriendlyName {
            get {
                return ResourceManager.GetString("TibiaGameSession_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tibia game sessions.
        /// </summary>
        public static string TibiaGameSession_FriendlyNamePlural {
            get {
                return ResourceManager.GetString("TibiaGameSession_FriendlyNamePlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tibia login session.
        /// </summary>
        public static string TibiaLoginSession_FriendlyName {
            get {
                return ResourceManager.GetString("TibiaLoginSession_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tibia login sessions.
        /// </summary>
        public static string TibiaLoginSession_FriendlyNamePlural {
            get {
                return ResourceManager.GetString("TibiaLoginSession_FriendlyNamePlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tibia server message.
        /// </summary>
        public static string TibiaServerMessage_FriendlyName {
            get {
                return ResourceManager.GetString("TibiaServerMessage_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tibia server messages.
        /// </summary>
        public static string TibiaServerMessage_FriendlyNamePlural {
            get {
                return ResourceManager.GetString("TibiaServerMessage_FriendlyNamePlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turns toward a cardinal direction without moving..
        /// </summary>
        public static string Turn_Description {
            get {
                return ResourceManager.GetString("Turn_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The cardinal direction to face..
        /// </summary>
        public static string Turn_Direction_Description {
            get {
                return ResourceManager.GetString("Turn_Direction_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Direction.
        /// </summary>
        public static string Turn_Direction_FriendlyName {
            get {
                return ResourceManager.GetString("Turn_Direction_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turn.
        /// </summary>
        public static string Turn_FriendlyName {
            get {
                return ResourceManager.GetString("Turn_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The session returned by Enter game..
        /// </summary>
        public static string Turn_GameSession_Description {
            get {
                return ResourceManager.GetString("Turn_GameSession_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game session.
        /// </summary>
        public static string Turn_GameSession_FriendlyName {
            get {
                return ResourceManager.GetString("Turn_GameSession_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turn without moving..
        /// </summary>
        public static string Turn_Summary {
            get {
                return ResourceManager.GetString("Turn_Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The container or hotkey slot the use was invoked from..
        /// </summary>
        public static string UseItem_ContainerIndex_Description {
            get {
                return ResourceManager.GetString("UseItem_ContainerIndex_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Container index.
        /// </summary>
        public static string UseItem_ContainerIndex_FriendlyName {
            get {
                return ResourceManager.GetString("UseItem_ContainerIndex_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uses an item at the given map position..
        /// </summary>
        public static string UseItem_Description {
            get {
                return ResourceManager.GetString("UseItem_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use item.
        /// </summary>
        public static string UseItem_FriendlyName {
            get {
                return ResourceManager.GetString("UseItem_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The session returned by Enter game..
        /// </summary>
        public static string UseItem_GameSession_Description {
            get {
                return ResourceManager.GetString("UseItem_GameSession_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game session.
        /// </summary>
        public static string UseItem_GameSession_FriendlyName {
            get {
                return ResourceManager.GetString("UseItem_GameSession_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The item's server id..
        /// </summary>
        public static string UseItem_ItemId_Description {
            get {
                return ResourceManager.GetString("UseItem_ItemId_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item ID.
        /// </summary>
        public static string UseItem_ItemId_FriendlyName {
            get {
                return ResourceManager.GetString("UseItem_ItemId_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The item's position within the tile stack..
        /// </summary>
        public static string UseItem_StackPosition_Description {
            get {
                return ResourceManager.GetString("UseItem_StackPosition_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stack position.
        /// </summary>
        public static string UseItem_StackPosition_FriendlyName {
            get {
                return ResourceManager.GetString("UseItem_StackPosition_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use an item..
        /// </summary>
        public static string UseItem_Summary {
            get {
                return ResourceManager.GetString("UseItem_Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The item's X map coordinate..
        /// </summary>
        public static string UseItem_X_Description {
            get {
                return ResourceManager.GetString("UseItem_X_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to X.
        /// </summary>
        public static string UseItem_X_FriendlyName {
            get {
                return ResourceManager.GetString("UseItem_X_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The item's Y map coordinate..
        /// </summary>
        public static string UseItem_Y_Description {
            get {
                return ResourceManager.GetString("UseItem_Y_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Y.
        /// </summary>
        public static string UseItem_Y_FriendlyName {
            get {
                return ResourceManager.GetString("UseItem_Y_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The item's floor (Z) coordinate..
        /// </summary>
        public static string UseItem_Z_Description {
            get {
                return ResourceManager.GetString("UseItem_Z_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Z.
        /// </summary>
        public static string UseItem_Z_FriendlyName {
            get {
                return ResourceManager.GetString("UseItem_Z_FriendlyName", resourceCulture);
            }
        }
    }
}
