//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PowerAutomate.Desktop.Modules.SQLite.Actions.Properties {
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PowerAutomate.Desktop.Modules.SQLite.Actions.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to SQLite could not open the database or execute the statement..
        /// </summary>
        public static string Error_DatabaseError_Description {
            get {
                return ResourceManager.GetString("Error_DatabaseError_Description", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to SQLite database error.
        /// </summary>
        public static string Error_DatabaseError_FriendlyName {
            get {
                return ResourceManager.GetString("Error_DatabaseError_FriendlyName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The database path, SQL statement, or parameters are invalid..
        /// </summary>
        public static string Error_InvalidArgumentError_Description {
            get {
                return ResourceManager.GetString("Error_InvalidArgumentError_Description", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Invalid input.
        /// </summary>
        public static string Error_InvalidArgumentError_FriendlyName {
            get {
                return ResourceManager.GetString("Error_InvalidArgumentError_FriendlyName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Number of rows changed by the statement..
        /// </summary>
        public static string Execute_AffectedRows_Description {
            get {
                return ResourceManager.GetString("Execute_AffectedRows_Description", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Affected rows.
        /// </summary>
        public static string Execute_AffectedRows_FriendlyName {
            get {
                return ResourceManager.GetString("Execute_AffectedRows_FriendlyName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Allow creation of the database file if it does not exist..
        /// </summary>
        public static string Execute_AllowCreate_Description {
            get {
                return ResourceManager.GetString("Execute_AllowCreate_Description", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Create database if missing.
        /// </summary>
        public static string Execute_AllowCreate_FriendlyName {
            get {
                return ResourceManager.GetString("Execute_AllowCreate_FriendlyName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Absolute path to a SQLite database file..
        /// </summary>
        public static string Execute_DatabasePath_Description {
            get {
                return ResourceManager.GetString("Execute_DatabasePath_Description", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Database path.
        /// </summary>
        public static string Execute_DatabasePath_FriendlyName {
            get {
                return ResourceManager.GetString("Execute_DatabasePath_FriendlyName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Execute a statement against a SQLite database..
        /// </summary>
        public static string Execute_Description {
            get {
                return ResourceManager.GetString("Execute_Description", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Execute SQLite statement.
        /// </summary>
        public static string Execute_FriendlyName {
            get {
                return ResourceManager.GetString("Execute_FriendlyName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Optional data table with Name and Value columns for bound parameters..
        /// </summary>
        public static string Execute_Parameters_Description {
            get {
                return ResourceManager.GetString("Execute_Parameters_Description", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Parameters.
        /// </summary>
        public static string Execute_Parameters_FriendlyName {
            get {
                return ResourceManager.GetString("Execute_Parameters_FriendlyName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to SQL statement with optional named placeholders..
        /// </summary>
        public static string Execute_Sql_Description {
            get {
                return ResourceManager.GetString("Execute_Sql_Description", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to SQL statement.
        /// </summary>
        public static string Execute_Sql_FriendlyName {
            get {
                return ResourceManager.GetString("Execute_Sql_FriendlyName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Run a parameterized SQLite statement..
        /// </summary>
        public static string Execute_Summary {
            get {
                return ResourceManager.GetString("Execute_Summary", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Absolute path to an existing SQLite database file..
        /// </summary>
        public static string Query_DatabasePath_Description {
            get {
                return ResourceManager.GetString("Query_DatabasePath_Description", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Database path.
        /// </summary>
        public static string Query_DatabasePath_FriendlyName {
            get {
                return ResourceManager.GetString("Query_DatabasePath_FriendlyName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Read rows from an existing SQLite database..
        /// </summary>
        public static string Query_Description {
            get {
                return ResourceManager.GetString("Query_Description", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Query SQLite database.
        /// </summary>
        public static string Query_FriendlyName {
            get {
                return ResourceManager.GetString("Query_FriendlyName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Optional data table with Name and Value columns for bound parameters..
        /// </summary>
        public static string Query_Parameters_Description {
            get {
                return ResourceManager.GetString("Query_Parameters_Description", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Parameters.
        /// </summary>
        public static string Query_Parameters_FriendlyName {
            get {
                return ResourceManager.GetString("Query_Parameters_FriendlyName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Rows returned by the query as a data table..
        /// </summary>
        public static string Query_Result_Description {
            get {
                return ResourceManager.GetString("Query_Result_Description", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Query result.
        /// </summary>
        public static string Query_Result_FriendlyName {
            get {
                return ResourceManager.GetString("Query_Result_FriendlyName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to SQL query with optional named placeholders..
        /// </summary>
        public static string Query_Sql_Description {
            get {
                return ResourceManager.GetString("Query_Sql_Description", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to SQL query.
        /// </summary>
        public static string Query_Sql_FriendlyName {
            get {
                return ResourceManager.GetString("Query_Sql_FriendlyName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Run a parameterized SQLite query..
        /// </summary>
        public static string Query_Summary {
            get {
                return ResourceManager.GetString("Query_Summary", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Work with local SQLite databases..
        /// </summary>
        public static string SQLite_Description {
            get {
                return ResourceManager.GetString("SQLite_Description", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to SQLite.
        /// </summary>
        public static string SQLite_FriendlyName {
            get {
                return ResourceManager.GetString("SQLite_FriendlyName", resourceCulture);
            }
        }
    }
}
