name: PowerAutomate.Desktop.Modules-Nightly

on:
  schedule:
    - cron: '0 0 * * *'

env:
  CONFIGURATION: "Release"
  ENVIRONMENT: "Production"

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout
      if: ${{ success() }}
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Setup MSBuild
      if: ${{ success() }}
      uses: microsoft/setup-msbuild@v1.3.1

    - name: Restore solution
      if: ${{ success() }}
      run: msbuild src\PowerAutomate.Desktop.sln -target:restore -property:Configuration=${{ env.CONFIGURATION }} -property:Environment=${{ env.ENVIRONMENT }}

    - name: Build solution
      if: ${{ success() }}
      run: msbuild src\PowerAutomate.Desktop.sln -target:rebuild -property:Configuration=${{ env.CONFIGURATION }} -property:Environment=${{ env.ENVIRONMENT }}

    - name: Run unit tests
      if: ${{ success() }}
      run: dotnet test src\PowerAutomate.Desktop.sln